---
title: Analysis
description: Here we provide a detailed analysis using more sophisticated statistics techniques.
toc: true
draft: false
---
# The question we want to address 

- The primary focus of this research is to explore the relationship between an individual's total income and their rental expenditures.
  - The analysis aims to determine how rental spending adjusts in response to changes in income levels.
  - Both linear and nonlinear models are employed to elucidate the connection between these variables.
  - Additionally, the study considers racial differences, examining how the coefficients vary among different racial groups.
  - A time series regression model is utilized to account for temporal variations in this relationship.
  
# Models and Inferences 

- Simple Linear Regression Model (Based on 2022 Data) – Detail analysis and plots refer to class blog 4 
  - The initial model fitting aimed to determine the potential worth of exploring the relationship between the predictor and response. 
  - The findings indicate that for every $1,000 increase in income, there is an associated increase of approximately 5.3213 units in the response variable on average.
  - The coefficient of this primary predictor, along with the intercept, has shown statistical significance.
  - Nonetheless, this initial model provides only a preliminary look at the relationship. A more comprehensive analysis will involve incorporating additional control variables.
  
- Multiple Linear Regression Model (Using the 2022 Dataset) -- For details, see class blog 4.
  - This expanded model included additional confounding variables, improving upon the simple linear regression framework.
  - The correlation matrix was utilized to select potential control variables as well as revealing variables that may potenitally pose a multicollinearity issue.
  - Upon fitting the multiple linear regression (MLR) model, 'Kitchen' was excluded due to its statistical insignificance, as evidenced by a notably high p-value. While 'Employment Status' also showed a non-significant p-value, it was not as pronounced as with 'Kitchen'. It is speculated that there might be an interaction effect between 'Employment Status' and variables such as 'Income' or 'FTOTINC', which will be further explored. 
  - A multicollinearity review was conducted, leading to the exclusion of 'FTOTINC' to mitigate overfitting.
  - Control variables were selected and confirmed.
  - Upon reviewing the statistical output, all coefficients were found to be significant, and the adjusted R-squared indicated a satisfactory model fit.
  - The model concludes that for every $1,000 increase in total income (INCTOT), there is an expected increase of 5.1111 units in the response variable, holding all other variables unchanged.
  - The residual plot showed signs of heteroscedasticity, suggesting the need for further model adjustments, such as adding interaction terms or applying logarithmic transformations to key regressor and response variables.
  
- **Log-Log Regression Model** (Utilizing the 2022 Dataset) -- Detail in class blog 4
  - Both the predictor and response variables underwent log transformation as their distributions are extremely right skewed (talked in data page)
  - Outliers were identified and removed from the analysis (also talked in data page, showed the density plot)
  - Fit the cleaned variables and do the model again.
  - All variables demonstrated statistical significance.
  - The residual plot suggested an acceptable fit.
  
- Log-Log Regression Model with interaction terms (Utilizing the 2022 Dataset) -- Detail in class blog 4
  
- **Log-Log Regression Model** (Utilizing the 2000-2022 Dataset) -- Detail in class blog 5
  - Using the accepted model above to fit the dataset of each year 
  - All coefficients show to be statistically significant 
  - Plot the residual plot & comfirmed it is falling within an acceptable range.
  - Compare the coefficients change for each year, plot diagram see the trend 
  
- Log-Log Regression Model **by Race** (2022 Dataset) — Detail in class blog 6
  - The analysis stratified the data by race, applying the aforementioned Log-Log regression approach.
  - It provided detailed coefficients for each racial category, examining the influence on the rent-income relationship.
  - The statistical significance of all coefficients was verified, with residual plots falling within an acceptable range.
  


- Longitudinal Log-Log Regression Model **by Race** (2000-2022 Dataset) — Detail in class blog 6
  - This model extended the 2022 dataset analysis to explore how the rent-income relationship for each racial group has evolved from 2000 to 2022.
  - Trends over time for each race were charted to illustrate these dynamics.
  - Similar to the 2022 model, the coefficients were found to be statistically significant and the residual plots falling within an acceptable range.
  
- Time series model (using 2000-2022 dataset) -- Detail in class blog 7



```{r}
library(tidyr)
library(broom)
library(dplyr)
library(here)
library(gt)
library(purrr)
data_path <- here("dataset", "data_twenty_clean.csv")
data_path1 <- here("dataset", "latest_clean.csv")
library(readr)
data_twenty <- read_csv(data_path,show_col_types = FALSE) 
data_2022 <- read_csv(data_path1,show_col_types = FALSE) 
library(ggplot2)
library(knitr)
library(lme4)
library(broom.mixed)
```






























  


------------------------------------------------------------------------

## Rubric: On this page

You will

-   Introduce what motivates your Data Analysis (DA)
    -   Which variables and relationships are you most interested in?
    -   What questions are you interested in answering?
    -   Provide context for the rest of the page. This will include figures/tables that illustrate aspects of the data of your question.
-   Modeling and Inference
    -   The page will include some kind of formal statistical model. This could be a linear regression, logistic regression, or another modeling framework.
    -   Explain the ideas and techniques you used to choose the predictors for your model. (Think about including interaction terms and other transformations of your variables.)
    -   Describe the results of your modelling and make sure to give a sense of the uncertainty in your estimates and conclusions.
-   Explain the flaws and limitations of your analysis
    -   Are there some assumptions that you needed to make that might not hold? Is there other data that would help to answer your questions?
-   Clarity Figures
    -   Are your figures/tables/results easy to read, informative, without problems like overplotting, hard-to-read labels, etc?
    -   Each figure should provide a key insight. Too many figures or other data summaries can detract from this. (While not a hard limit, around 5 total figures is probably a good target.)
    -   Default `lm` output and plots are typically not acceptable.
-   Clarity of Explanations
    -   How well do you explain each figure/result?
    -   Do you provide interpretations that suggest further analysis or explanations for observed phenomenon?
-   Organization and cleanliness.
    -   Make sure to remove excessive warnings, hide most or all code, organize with sections or multiple pages, use bullets, etc.
    -   This page should be self-contained, i.e. provide a description of the relevant data.
