<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Here we provide a detailed analysis using more sophisticated statistics techniques.">

<title>MA [46]15 Final Project by Team 9 - Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="site_libs/datatables-binding-0.33/datatables.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">MA [46]15 Final Project by Team 9</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./big_picture.html" rel="" target="">
 <span class="menu-text">The Price of Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./analysis.html" rel="" target="" aria-current="page">
 <span class="menu-text">Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data.html" rel="" target="">
 <span class="menu-text">Data</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-question-we-want-to-address" id="toc-the-question-we-want-to-address" class="nav-link active" data-scroll-target="#the-question-we-want-to-address">The question we want to address</a></li>
  <li><a href="#models-and-inferences-first-dataset" id="toc-models-and-inferences-first-dataset" class="nav-link" data-scroll-target="#models-and-inferences-first-dataset">Models and Inferences (First dataset)</a></li>
  <li><a href="#outline" id="toc-outline" class="nav-link" data-scroll-target="#outline">Outline</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression-model-based-on-2022-data" id="toc-simple-linear-regression-model-based-on-2022-data" class="nav-link" data-scroll-target="#simple-linear-regression-model-based-on-2022-data">1. Simple Linear Regression Model (Based on 2022 Data)</a>
  <ul class="collapse">
  <li><a href="#model-overview" id="toc-model-overview" class="nav-link" data-scroll-target="#model-overview">Model Overview:</a></li>
  <li><a href="#model-findings" id="toc-model-findings" class="nav-link" data-scroll-target="#model-findings">Model Findings:</a></li>
  <li><a href="#statistical-significance" id="toc-statistical-significance" class="nav-link" data-scroll-target="#statistical-significance">Statistical Significance:</a></li>
  <li><a href="#model-discussion" id="toc-model-discussion" class="nav-link" data-scroll-target="#model-discussion">Model Discussion:</a></li>
  </ul></li>
  <li><a href="#multiple-linear-regression-model-based-on-2022-data" id="toc-multiple-linear-regression-model-based-on-2022-data" class="nav-link" data-scroll-target="#multiple-linear-regression-model-based-on-2022-data">2. Multiple Linear Regression Model (Based on 2022 Data)</a>
  <ul class="collapse">
  <li><a href="#model-overview-1" id="toc-model-overview-1" class="nav-link" data-scroll-target="#model-overview-1">Model Overview:</a></li>
  <li><a href="#variable-selection" id="toc-variable-selection" class="nav-link" data-scroll-target="#variable-selection">Variable Selection:</a></li>
  <li><a href="#inference" id="toc-inference" class="nav-link" data-scroll-target="#inference">Inference:</a></li>
  <li><a href="#inference-1" id="toc-inference-1" class="nav-link" data-scroll-target="#inference-1">Inference:</a></li>
  <li><a href="#statistical-performance" id="toc-statistical-performance" class="nav-link" data-scroll-target="#statistical-performance">Statistical Performance:</a></li>
  <li><a href="#discussion-of-the-model" id="toc-discussion-of-the-model" class="nav-link" data-scroll-target="#discussion-of-the-model">Discussion of the Model:</a></li>
  </ul></li>
  <li><a href="#log-log-regression-model" id="toc-log-log-regression-model" class="nav-link" data-scroll-target="#log-log-regression-model">3. Log-Log Regression Model</a>
  <ul class="collapse">
  <li><a href="#model-overview-2" id="toc-model-overview-2" class="nav-link" data-scroll-target="#model-overview-2">Model Overview:</a></li>
  <li><a href="#inference-2" id="toc-inference-2" class="nav-link" data-scroll-target="#inference-2">Inference:</a></li>
  <li><a href="#statistical-performance-1" id="toc-statistical-performance-1" class="nav-link" data-scroll-target="#statistical-performance-1">Statistical Performance:</a></li>
  <li><a href="#model-discussion-1" id="toc-model-discussion-1" class="nav-link" data-scroll-target="#model-discussion-1">Model Discussion:</a></li>
  </ul></li>
  <li><a href="#log-log-regression-model-by-race" id="toc-log-log-regression-model-by-race" class="nav-link" data-scroll-target="#log-log-regression-model-by-race">4. Log-Log Regression Model by Race</a>
  <ul class="collapse">
  <li><a href="#model-overview-3" id="toc-model-overview-3" class="nav-link" data-scroll-target="#model-overview-3">Model Overview</a></li>
  <li><a href="#model-inferences" id="toc-model-inferences" class="nav-link" data-scroll-target="#model-inferences">Model Inferences:</a></li>
  <li><a href="#statistical-performance-assessment" id="toc-statistical-performance-assessment" class="nav-link" data-scroll-target="#statistical-performance-assessment">Statistical Performance Assessment</a></li>
  <li><a href="#discussion-of-the-model-1" id="toc-discussion-of-the-model-1" class="nav-link" data-scroll-target="#discussion-of-the-model-1">Discussion of the model:</a></li>
  </ul></li>
  <li><a href="#enhanced-log-log-regression-model-with-interaction-terms-based-on-the-2022-dataset" id="toc-enhanced-log-log-regression-model-with-interaction-terms-based-on-the-2022-dataset" class="nav-link" data-scroll-target="#enhanced-log-log-regression-model-with-interaction-terms-based-on-the-2022-dataset">5. Enhanced Log-Log Regression Model with Interaction Terms (Based on the 2022 Dataset)</a>
  <ul class="collapse">
  <li><a href="#model-rationale" id="toc-model-rationale" class="nav-link" data-scroll-target="#model-rationale">Model Rationale:</a></li>
  <li><a href="#variable-selection-and-refinement" id="toc-variable-selection-and-refinement" class="nav-link" data-scroll-target="#variable-selection-and-refinement">Variable Selection and Refinement:</a></li>
  <li><a href="#model-inferences-1" id="toc-model-inferences-1" class="nav-link" data-scroll-target="#model-inferences-1">Model Inferences:</a></li>
  <li><a href="#statistical-performance-assessment-1" id="toc-statistical-performance-assessment-1" class="nav-link" data-scroll-target="#statistical-performance-assessment-1">Statistical Performance Assessment:</a></li>
  <li><a href="#discussion-of-the-model-2" id="toc-discussion-of-the-model-2" class="nav-link" data-scroll-target="#discussion-of-the-model-2">Discussion of the model:</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#models-and-inferences-merged-dataset" id="toc-models-and-inferences-merged-dataset" class="nav-link" data-scroll-target="#models-and-inferences-merged-dataset">Models and Inferences (Merged dataset)</a>
  <ul class="collapse">
  <li><a href="#outline-1" id="toc-outline-1" class="nav-link" data-scroll-target="#outline-1">Outline</a></li>
  <li><a href="#log-log-regression-model-by-year" id="toc-log-log-regression-model-by-year" class="nav-link" data-scroll-target="#log-log-regression-model-by-year">1. Log-Log Regression Model by YEAR</a>
  <ul class="collapse">
  <li><a href="#model-overview-4" id="toc-model-overview-4" class="nav-link" data-scroll-target="#model-overview-4">Model Overview:</a></li>
  <li><a href="#model-inferences-2" id="toc-model-inferences-2" class="nav-link" data-scroll-target="#model-inferences-2">Model Inferences:</a></li>
  <li><a href="#statistical-performance-assessment-2" id="toc-statistical-performance-assessment-2" class="nav-link" data-scroll-target="#statistical-performance-assessment-2">Statistical Performance Assessment:</a></li>
  </ul></li>
  <li><a href="#longitudinal-log-log-regression-model-by-race" id="toc-longitudinal-log-log-regression-model-by-race" class="nav-link" data-scroll-target="#longitudinal-log-log-regression-model-by-race">2. Longitudinal Log-Log Regression Model by Race</a>
  <ul class="collapse">
  <li><a href="#model-overview-5" id="toc-model-overview-5" class="nav-link" data-scroll-target="#model-overview-5">Model Overview:</a></li>
  <li><a href="#model-inferences-3" id="toc-model-inferences-3" class="nav-link" data-scroll-target="#model-inferences-3">Model Inferences:</a></li>
  <li><a href="#statistical-performance-2" id="toc-statistical-performance-2" class="nav-link" data-scroll-target="#statistical-performance-2">Statistical Performance:</a></li>
  </ul></li>
  <li><a href="#time-series-model" id="toc-time-series-model" class="nav-link" data-scroll-target="#time-series-model">3.Time series model</a></li>
  <li><a href="#rubric-on-this-page" id="toc-rubric-on-this-page" class="nav-link" data-scroll-target="#rubric-on-this-page">Rubric: On this page</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis</h1>
</div>

<div>
  <div class="description">
    Here we provide a detailed analysis using more sophisticated statistics techniques.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="the-question-we-want-to-address" class="level1">
<h1>The question we want to address</h1>
<ul>
<li>The primary focus of this research is to explore the relationship between an individual’s total income and their rental expenditures.
<ul>
<li>The analysis aims to determine how rental spending adjusts in response to changes in income levels.</li>
<li>Both linear and nonlinear models are employed to elucidate the connection between these variables.</li>
<li>Additionally, the study considers racial differences, examining how the coefficients vary among different racial groups.</li>
<li>A time series regression model is utilized to account for temporal variations in this relationship.</li>
</ul></li>
</ul>
</section>
<section id="models-and-inferences-first-dataset" class="level1">
<h1>Models and Inferences (First dataset)</h1>
</section>
<section id="outline" class="level1">
<h1>Outline</h1>
<ol type="1">
<li>Simple Linear Regression Model (Based on 2022 Data)</li>
<li>Multiple Linear Regression Model (Based on 2022 Data)</li>
<li>Log-Log Regression Model (Utilizing the 2022 Dataset)</li>
<li>Log-Log Regression Model with interaction terms (Utilizing the 2022 Dataset)</li>
</ol>
<section id="simple-linear-regression-model-based-on-2022-data" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-model-based-on-2022-data">1. Simple Linear Regression Model (Based on 2022 Data)</h2>
<section id="model-overview" class="level3">
<h3 class="anchored" data-anchor-id="model-overview">Model Overview:</h3>
<ul>
<li>This model explores the relationship between the predictor (income) and the response (rent), providing insights into their potential correlation. Detailed analysis and visualizations are discussed in Class Blog 4.</li>
</ul>
</section>
<section id="model-findings" class="level3">
<h3 class="anchored" data-anchor-id="model-findings">Model Findings:</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1329.7165501</td>
<td style="text-align: right;">15.8008996</td>
<td style="text-align: right;">84.15448</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">INCTOT</td>
<td style="text-align: right;">0.0057046</td>
<td style="text-align: right;">0.0002248</td>
<td style="text-align: right;">25.38011</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The model suggests that an increase of $1,000 in income is associated with an average increase of approximately 5.3213 units in the rent variable.</li>
</ul>
</section>
<section id="statistical-significance" class="level3">
<h3 class="anchored" data-anchor-id="statistical-significance">Statistical Significance:</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.1108854</td>
<td style="text-align: right;">0.1107132</td>
<td style="text-align: right;">884.7833</td>
<td style="text-align: right;">644.1498</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-42390.52</td>
<td style="text-align: right;">84787.04</td>
<td style="text-align: right;">84806.69</td>
<td style="text-align: right;">4043376235</td>
<td style="text-align: right;">5165</td>
<td style="text-align: right;">5167</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The coefficients, including the primary predictor and the intercept, have shown statistical significance, indicating reliable estimations.</li>
</ul>
</section>
<section id="model-discussion" class="level3">
<h3 class="anchored" data-anchor-id="model-discussion">Model Discussion:</h3>
<ul>
<li>Although this preliminary model sheds light on the relationship between income and rent, further analysis should include additional variables to enhance understanding and accuracy.</li>
</ul>
</section>
</section>
<section id="multiple-linear-regression-model-based-on-2022-data" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression-model-based-on-2022-data">2. Multiple Linear Regression Model (Based on 2022 Data)</h2>
<section id="model-overview-1" class="level3">
<h3 class="anchored" data-anchor-id="model-overview-1">Model Overview:</h3>
<ul>
<li>This model enhances the simple linear regression by incorporating additional confounding variables to refine our analysis.</li>
<li>For more details, refer to Class Blog 4.</li>
<li>This expanded model builds upon the initial simple linear regression framework.</li>
</ul>
</section>
<section id="variable-selection" class="level3">
<h3 class="anchored" data-anchor-id="variable-selection">Variable Selection:</h3>
<ul>
<li>A correlation matrix was used to identify control variables and to detect potential multi-collinearity issues.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">INCTOT</th>
<th style="text-align: right;">ROOMS</th>
<th style="text-align: right;">NFAMS</th>
<th style="text-align: right;">AGE</th>
<th style="text-align: right;">FTOTINC</th>
<th style="text-align: right;">RENTGRS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">INCTOT</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">-0.0149409</td>
<td style="text-align: right;">-0.0313099</td>
<td style="text-align: right;">-0.0077964</td>
<td style="text-align: right;">0.7282638</td>
<td style="text-align: right;">0.3329946</td>
</tr>
<tr class="even">
<td style="text-align: left;">ROOMS</td>
<td style="text-align: right;">-0.0149409</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.1631221</td>
<td style="text-align: right;">-0.0439707</td>
<td style="text-align: right;">0.1083906</td>
<td style="text-align: right;">0.1406264</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NFAMS</td>
<td style="text-align: right;">-0.0313099</td>
<td style="text-align: right;">0.1631221</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">-0.1405046</td>
<td style="text-align: right;">-0.0924716</td>
<td style="text-align: right;">0.0881204</td>
</tr>
<tr class="even">
<td style="text-align: left;">AGE</td>
<td style="text-align: right;">-0.0077964</td>
<td style="text-align: right;">-0.0439707</td>
<td style="text-align: right;">-0.1405046</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">-0.0768613</td>
<td style="text-align: right;">-0.0870537</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FTOTINC</td>
<td style="text-align: right;">0.7282638</td>
<td style="text-align: right;">0.1083906</td>
<td style="text-align: right;">-0.0924716</td>
<td style="text-align: right;">-0.0768613</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.4448424</td>
</tr>
<tr class="even">
<td style="text-align: left;">RENTGRS</td>
<td style="text-align: right;">0.3329946</td>
<td style="text-align: right;">0.1406264</td>
<td style="text-align: right;">0.0881204</td>
<td style="text-align: right;">-0.0870537</td>
<td style="text-align: right;">0.4448424</td>
<td style="text-align: right;">1.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>After fitting the multiple linear regression (MLR) model, ‘Kitchen’ was removed due to its statistical insignificance, indicated by a high p-value. ‘Employment Status’, although not as critical, also showed a non-significant p-value and is suspected to interact with variables like ‘Income’ or ‘FTOTINC’. This interaction will be explored further.</li>
<li>A review of multicollinearity prompted the removal of ‘FTOTINC’ to prevent model overfitting.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">GVIF</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">GVIF^(1/(2*Df))</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">INCTOT</td>
<td style="text-align: right;">2.317240</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.522248</td>
</tr>
<tr class="even">
<td style="text-align: left;">KITCHEN</td>
<td style="text-align: right;">1.023481</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.011673</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ROOMS</td>
<td style="text-align: right;">1.108739</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.052967</td>
</tr>
<tr class="even">
<td style="text-align: left;">NFAMS</td>
<td style="text-align: right;">1.111046</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.054062</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AGE</td>
<td style="text-align: right;">2.074406</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.440280</td>
</tr>
<tr class="even">
<td style="text-align: left;">MARST</td>
<td style="text-align: right;">1.856902</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.063846</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACE</td>
<td style="text-align: right;">1.198063</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1.011358</td>
</tr>
<tr class="even">
<td style="text-align: left;">EMPSTAT</td>
<td style="text-align: right;">1.576945</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.120609</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FTOTINC</td>
<td style="text-align: right;">2.385884</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.544631</td>
</tr>
<tr class="even">
<td style="text-align: left;">REGION_CLASSIFIED</td>
<td style="text-align: right;">1.130442</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.020645</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The selection and validation of control variables were systematically conducted.</li>
</ul>
</section>
<section id="inference" class="level3">
<h3 class="anchored" data-anchor-id="inference">Inference:</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.2317473</td>
<td style="text-align: right;">0.2284616</td>
<td style="text-align: right;">824.1282</td>
<td style="text-align: right;">70.53243</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">-42013.05</td>
<td style="text-align: right;">84074.11</td>
<td style="text-align: right;">84231.31</td>
<td style="text-align: right;">3493739342</td>
<td style="text-align: right;">5144</td>
<td style="text-align: right;">5167</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="inference-1" class="level3">
<h3 class="anchored" data-anchor-id="inference-1">Inference:</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 44%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">192.4680339</td>
<td style="text-align: right;">125.4185543</td>
<td style="text-align: right;">1.5346057</td>
<td style="text-align: right;">0.1249422</td>
</tr>
<tr class="even">
<td style="text-align: left;">INCTOT</td>
<td style="text-align: right;">0.0051585</td>
<td style="text-align: right;">0.0002198</td>
<td style="text-align: right;">23.4696962</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ROOMS</td>
<td style="text-align: right;">62.4778275</td>
<td style="text-align: right;">5.8448723</td>
<td style="text-align: right;">10.6893401</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">NFAMS</td>
<td style="text-align: right;">88.3019863</td>
<td style="text-align: right;">16.3854438</td>
<td style="text-align: right;">5.3890506</td>
<td style="text-align: right;">0.0000001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AGE</td>
<td style="text-align: right;">-3.0743841</td>
<td style="text-align: right;">0.8875968</td>
<td style="text-align: right;">-3.4637171</td>
<td style="text-align: right;">0.0005371</td>
</tr>
<tr class="even">
<td style="text-align: left;">MARSTMarried, spouse absent</td>
<td style="text-align: right;">94.9406492</td>
<td style="text-align: right;">75.3701889</td>
<td style="text-align: right;">1.2596578</td>
<td style="text-align: right;">0.2078500</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MARSTMarried, spouse present</td>
<td style="text-align: right;">270.2800166</td>
<td style="text-align: right;">38.1022679</td>
<td style="text-align: right;">7.0935414</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">MARSTNever married/single</td>
<td style="text-align: right;">133.7032021</td>
<td style="text-align: right;">39.1610925</td>
<td style="text-align: right;">3.4141847</td>
<td style="text-align: right;">0.0006447</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MARSTSeparated</td>
<td style="text-align: right;">-12.8753038</td>
<td style="text-align: right;">72.7354147</td>
<td style="text-align: right;">-0.1770156</td>
<td style="text-align: right;">0.8595031</td>
</tr>
<tr class="even">
<td style="text-align: left;">MARSTWidowed</td>
<td style="text-align: right;">165.1710342</td>
<td style="text-align: right;">58.5735588</td>
<td style="text-align: right;">2.8198907</td>
<td style="text-align: right;">0.0048224</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACEBlack/African American</td>
<td style="text-align: right;">311.1982598</td>
<td style="text-align: right;">110.5848687</td>
<td style="text-align: right;">2.8141125</td>
<td style="text-align: right;">0.0049098</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEChinese</td>
<td style="text-align: right;">442.5579390</td>
<td style="text-align: right;">144.9951127</td>
<td style="text-align: right;">3.0522266</td>
<td style="text-align: right;">0.0022831</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACEJapanese</td>
<td style="text-align: right;">359.8914300</td>
<td style="text-align: right;">231.9929731</td>
<td style="text-align: right;">1.5513032</td>
<td style="text-align: right;">0.1208906</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEOther Asian or Pacific Islander</td>
<td style="text-align: right;">497.1734167</td>
<td style="text-align: right;">116.4670507</td>
<td style="text-align: right;">4.2687903</td>
<td style="text-align: right;">0.0000200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACEOther race, nec</td>
<td style="text-align: right;">343.5788878</td>
<td style="text-align: right;">112.1486813</td>
<td style="text-align: right;">3.0636017</td>
<td style="text-align: right;">0.0021982</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEThree or more major races</td>
<td style="text-align: right;">498.8640790</td>
<td style="text-align: right;">156.7572625</td>
<td style="text-align: right;">3.1823985</td>
<td style="text-align: right;">0.0014693</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACETwo major races</td>
<td style="text-align: right;">379.9573896</td>
<td style="text-align: right;">111.1079215</td>
<td style="text-align: right;">3.4197147</td>
<td style="text-align: right;">0.0006317</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEWhite</td>
<td style="text-align: right;">390.0560268</td>
<td style="text-align: right;">107.1130784</td>
<td style="text-align: right;">3.6415350</td>
<td style="text-align: right;">0.0002737</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EMPSTATNot in labour force</td>
<td style="text-align: right;">-16.1759159</td>
<td style="text-align: right;">33.5495389</td>
<td style="text-align: right;">-0.4821502</td>
<td style="text-align: right;">0.6297198</td>
</tr>
<tr class="even">
<td style="text-align: left;">EMPSTATUnemployed</td>
<td style="text-align: right;">55.6707902</td>
<td style="text-align: right;">69.1339994</td>
<td style="text-align: right;">0.8052592</td>
<td style="text-align: right;">0.4207073</td>
</tr>
<tr class="odd">
<td style="text-align: left;">REGION_CLASSIFIEDNORTHEAST</td>
<td style="text-align: right;">404.8892183</td>
<td style="text-align: right;">39.7506791</td>
<td style="text-align: right;">10.1857183</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">REGION_CLASSIFIEDSOUTH</td>
<td style="text-align: right;">253.5626804</td>
<td style="text-align: right;">34.6492894</td>
<td style="text-align: right;">7.3179763</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">REGION_CLASSIFIEDWEST</td>
<td style="text-align: right;">719.8277912</td>
<td style="text-align: right;">36.9311828</td>
<td style="text-align: right;">19.4910570</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The analysis reveals that a unit increase in total income (INCTOT) is associated with an average increase of 0.0005482 in gross rent (RENTGRS), assuming other variables are constant.</li>
</ul>
</section>
<section id="statistical-performance" class="level3">
<h3 class="anchored" data-anchor-id="statistical-performance">Statistical Performance:</h3>
<ul>
<li>The R-squared value of 0.28 indicates that approximately 28% of the variance in the dependent variable (gross rent) is explained by the model, which is a considerable improvement compared to the simple linear regression.</li>
<li>The adjusted R-squared value of 0.2807292 closely mirrors the R-squared value, suggesting that the additional predictors are effectively contributing valuable information.</li>
<li>A F-statistic value of 98.57 and a p-value of 0 confirm the statistical significance of the model, suggesting that the regression results are highly unlikely to occur by chance.</li>
</ul>
</section>
<section id="discussion-of-the-model" class="level3">
<h3 class="anchored" data-anchor-id="discussion-of-the-model">Discussion of the Model:</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>The residual plot shows signs of heteroskedasticity, as the spread of residuals increases with the fitted values. The presence of patterns in the residuals suggests a non-linear relationship between predictors and the response, indicating potential violations of linear model assumptions.</li>
<li>These issues could be attributed to large values and skewness in the data variables, leading us to consider alternative models, such as a log-log transformation to address these discrepancies.</li>
</ul>
</section>
</section>
<section id="log-log-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="log-log-regression-model">3. Log-Log Regression Model</h2>
<section id="model-overview-2" class="level3">
<h3 class="anchored" data-anchor-id="model-overview-2">Model Overview:</h3>
<ul>
<li>A thorough explanation is provided in Class Blog 4.</li>
<li>Predictor and response variables underwent log transformation to correct for right skewness, as elaborated on the data page.</li>
<li>Density plots were used to identify and remove outliers for a more accurate model.</li>
<li>A reanalysis was conducted post data cleansing to assess the impact of log-transformed variables.</li>
</ul>
</section>
<section id="inference-2" class="level3">
<h3 class="anchored" data-anchor-id="inference-2">Inference:</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 46%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">5.1300453</td>
<td style="text-align: right;">0.1067311</td>
<td style="text-align: right;">48.0651464</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">log_INCTOT</td>
<td style="text-align: right;">0.1334422</td>
<td style="text-align: right;">0.0076099</td>
<td style="text-align: right;">17.5353005</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ROOMS</td>
<td style="text-align: right;">0.0417813</td>
<td style="text-align: right;">0.0036000</td>
<td style="text-align: right;">11.6060404</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">NFAMS</td>
<td style="text-align: right;">0.0329669</td>
<td style="text-align: right;">0.0100882</td>
<td style="text-align: right;">3.2678822</td>
<td style="text-align: right;">0.0010907</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AGE</td>
<td style="text-align: right;">-0.0035780</td>
<td style="text-align: right;">0.0005543</td>
<td style="text-align: right;">-6.4554553</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">MARSTMarried, spouse absent</td>
<td style="text-align: right;">0.1202752</td>
<td style="text-align: right;">0.0463969</td>
<td style="text-align: right;">2.5923119</td>
<td style="text-align: right;">0.0095603</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MARSTMarried, spouse present</td>
<td style="text-align: right;">0.2037563</td>
<td style="text-align: right;">0.0234393</td>
<td style="text-align: right;">8.6929177</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">MARSTNever married/single</td>
<td style="text-align: right;">0.1093599</td>
<td style="text-align: right;">0.0241056</td>
<td style="text-align: right;">4.5366957</td>
<td style="text-align: right;">0.0000058</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MARSTSeparated</td>
<td style="text-align: right;">0.0317849</td>
<td style="text-align: right;">0.0447714</td>
<td style="text-align: right;">0.7099382</td>
<td style="text-align: right;">0.4777746</td>
</tr>
<tr class="even">
<td style="text-align: left;">MARSTWidowed</td>
<td style="text-align: right;">0.1003713</td>
<td style="text-align: right;">0.0360489</td>
<td style="text-align: right;">2.7843077</td>
<td style="text-align: right;">0.0053838</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACEBlack/African American</td>
<td style="text-align: right;">0.2424072</td>
<td style="text-align: right;">0.0680509</td>
<td style="text-align: right;">3.5621460</td>
<td style="text-align: right;">0.0003712</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEChinese</td>
<td style="text-align: right;">0.2865844</td>
<td style="text-align: right;">0.0892336</td>
<td style="text-align: right;">3.2116179</td>
<td style="text-align: right;">0.0013280</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACEJapanese</td>
<td style="text-align: right;">0.3096517</td>
<td style="text-align: right;">0.1428069</td>
<td style="text-align: right;">2.1683238</td>
<td style="text-align: right;">0.0301798</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEOther Asian or Pacific Islander</td>
<td style="text-align: right;">0.3673317</td>
<td style="text-align: right;">0.0716731</td>
<td style="text-align: right;">5.1251000</td>
<td style="text-align: right;">0.0000003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACEOther race, nec</td>
<td style="text-align: right;">0.2807254</td>
<td style="text-align: right;">0.0690242</td>
<td style="text-align: right;">4.0670562</td>
<td style="text-align: right;">0.0000483</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEThree or more major races</td>
<td style="text-align: right;">0.3548441</td>
<td style="text-align: right;">0.0965187</td>
<td style="text-align: right;">3.6764279</td>
<td style="text-align: right;">0.0002389</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACETwo major races</td>
<td style="text-align: right;">0.2827093</td>
<td style="text-align: right;">0.0683784</td>
<td style="text-align: right;">4.1344834</td>
<td style="text-align: right;">0.0000361</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEWhite</td>
<td style="text-align: right;">0.2663832</td>
<td style="text-align: right;">0.0659283</td>
<td style="text-align: right;">4.0405009</td>
<td style="text-align: right;">0.0000541</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EMPSTATNot in labour force</td>
<td style="text-align: right;">-0.0361988</td>
<td style="text-align: right;">0.0222177</td>
<td style="text-align: right;">-1.6292740</td>
<td style="text-align: right;">0.1033163</td>
</tr>
<tr class="even">
<td style="text-align: left;">EMPSTATUnemployed</td>
<td style="text-align: right;">0.0756027</td>
<td style="text-align: right;">0.0430993</td>
<td style="text-align: right;">1.7541506</td>
<td style="text-align: right;">0.0794642</td>
</tr>
<tr class="odd">
<td style="text-align: left;">REGION_CLASSIFIEDNORTHEAST</td>
<td style="text-align: right;">0.2785550</td>
<td style="text-align: right;">0.0244342</td>
<td style="text-align: right;">11.4002308</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">REGION_CLASSIFIEDSOUTH</td>
<td style="text-align: right;">0.1916896</td>
<td style="text-align: right;">0.0213248</td>
<td style="text-align: right;">8.9890579</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">REGION_CLASSIFIEDWEST</td>
<td style="text-align: right;">0.4657014</td>
<td style="text-align: right;">0.0227049</td>
<td style="text-align: right;">20.5110144</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The model suggests that a 10% increase in income is predicted to raise rent by an average of 13.34%, with all other variables held constant, indicating income’s elasticity effect on rent.</li>
</ul>
</section>
<section id="statistical-performance-1" class="level3">
<h3 class="anchored" data-anchor-id="statistical-performance-1">Statistical Performance:</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.227         0.223 0.507      68.6 6.81e-267    22 -3813. 7673. 7830.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<ul>
<li>An adjusted R-squared value of 0.223, while modest, is considered adequate within the complex realms of social science and economics.</li>
<li>A very low p-value signifies the statistical significance of the model’s predictors.</li>
<li>The sigma value’s reduction points to a more precise model, albeit comparisons with non-logarithmic models are not straightforward due to scale differences.</li>
</ul>
</section>
<section id="model-discussion-1" class="level3">
<h3 class="anchored" data-anchor-id="model-discussion-1">Model Discussion:</h3>
<ol type="1">
<li>Linearity and Homoscedasticity:</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>The absence of a systematic pattern in the residuals indicates a proper capture of the relationship between the predictors and response variable in the log-transformed model.</li>
<li>The spread of residuals is mostly consistent, though some widening at the extremes suggests minor heteroscedasticity. This is often a minor issue in economic data, reflecting the variability in higher income or rent brackets, and doesn’t significantly affect the model’s overall validity.</li>
<li>Residuals predominantly centering around the zero line signify no model bias, reinforcing the model’s accuracy.</li>
<li>A small number of potential outliers deviate from the main cluster, which is typical in large economic datasets and generally does not markedly impact the robust central trend captured by the model.</li>
</ul>
<ol start="2" type="1">
<li>Normality of Residuals:</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>The bulk of residuals align with the normality line on the Q-Q plot, with slight deviations at both ends.</li>
<li>These deviations, often seen in economic data due to outliers, do not substantially affect the model’s predictive capability.</li>
</ul>
<ol start="3" type="1">
<li>IID Errors:</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  log_model_2022
DW = 1.9775, p-value = 0.2092
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<ul>
<li>For Durbin-Watson Statistic, the result value close to 2 indicates no autocorrelation, implying that the errors are independent. And for a random scatter of residuals, without visible trends or cycles, supports the assumption of IID errors.</li>
</ul>
<ol start="4" type="1">
<li>Multicollinearity:</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">GVIF</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">GVIF^(1/(2*Df))</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">log_INCTOT</td>
<td style="text-align: right;">1.298351</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.139452</td>
</tr>
<tr class="even">
<td style="text-align: left;">ROOMS</td>
<td style="text-align: right;">1.069938</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.034378</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NFAMS</td>
<td style="text-align: right;">1.088234</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.043185</td>
</tr>
<tr class="even">
<td style="text-align: left;">AGE</td>
<td style="text-align: right;">2.109694</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.452479</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MARST</td>
<td style="text-align: right;">1.790805</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.059997</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACE</td>
<td style="text-align: right;">1.193223</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1.011102</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EMPSTAT</td>
<td style="text-align: right;">1.844666</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.165412</td>
</tr>
<tr class="even">
<td style="text-align: left;">REGION_CLASSIFIED</td>
<td style="text-align: right;">1.119686</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.019020</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The adjusted GVIF values, being all near or below the threshold of 1.5 after taking the root, demonstrate that the multicollinearity is likely not distorting the estimates in the regression model significantly. This implies that each predictor variable is providing unique information that is not overly redundant with other variables in the model.</li>
</ul>
<p><strong>Upon reviewing these diagnostic measures, the model is deemed well-fitted, and the derived conclusions are robust and reliable.</strong></p>
</section>
</section>
<section id="log-log-regression-model-by-race" class="level2">
<h2 class="anchored" data-anchor-id="log-log-regression-model-by-race">4. Log-Log Regression Model by Race</h2>
<section id="model-overview-3" class="level3">
<h3 class="anchored" data-anchor-id="model-overview-3">Model Overview</h3>
<ul>
<li>This analysis applies a stratified Log-Log regression approach, segregating data by race as detailed in Class Blog 6. It builds upon the strong foundational understanding from Section 3.</li>
</ul>
</section>
<section id="model-inferences" class="level3">
<h3 class="anchored" data-anchor-id="model-inferences">Model Inferences:</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">RACE</th>
<th style="text-align: right;">log_INCTOT_Coefficient</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">American Indian or Alaska Native</td>
<td style="text-align: right;">0.0937685</td>
</tr>
<tr class="even">
<td style="text-align: left;">Black/African American</td>
<td style="text-align: right;">0.0621126</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chinese</td>
<td style="text-align: right;">0.1915177</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other Asian or Pacific Islander</td>
<td style="text-align: right;">0.1050231</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other race, nec</td>
<td style="text-align: right;">0.0376731</td>
</tr>
<tr class="even">
<td style="text-align: left;">Three or more major races</td>
<td style="text-align: right;">0.1048730</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Two major races</td>
<td style="text-align: right;">0.0882288</td>
</tr>
<tr class="even">
<td style="text-align: left;">White</td>
<td style="text-align: right;">0.1676538</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><p>The coefficient for log_INCTOT shows notable variation across racial categories, which indicates the impact of income on rent varies by race.</p></li>
<li><p>The Chinese group demonstrates the highest log_INCTOT coefficient, indicating a particularly strong positive association between income and rent within this demographic.</p></li>
<li><p>American Indian or Alaska Native, Other Asian or Pacific Islander, Other race, nec, Three or more major races, and White categories show a range of coefficients, suggesting varied levels of positive association.</p></li>
<li><p>Black/African American and Two major races groups present with lower coefficients, hinting at a relatively weaker positive relationship.</p></li>
</ul>
</section>
<section id="statistical-performance-assessment" class="level3">
<h3 class="anchored" data-anchor-id="statistical-performance-assessment">Statistical Performance Assessment</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>

|RACE                             |term       |  estimate|   p.value|
|:--------------------------------|:----------|---------:|---------:|
|American Indian or Alaska Native |log_INCTOT | 0.0937685| 0.3138472|
|Black/African American           |log_INCTOT | 0.0621126| 0.0012082|
|Chinese                          |log_INCTOT | 0.1915177| 0.0428004|
|Other Asian or Pacific Islander  |log_INCTOT | 0.1050231| 0.0001647|
|Other race, nec                  |log_INCTOT | 0.0376731| 0.1041104|
|Three or more major races        |log_INCTOT | 0.1048730| 0.1615109|
|Two major races                  |log_INCTOT | 0.0882288| 0.0000441|
|White                            |log_INCTOT | 0.1676538| 0.0000000|</code></pre>
</div>
</div>
<ul>
<li><p>For most racial groups, the p-values indicate statistical significance (p &lt; 0.05), especially pronounced for Black/African American, Chinese, Other Asian or Pacific Islander, and White categories, implying a strong relationship between income and rent.</p></li>
<li><p>The higher p-value for American Indian or Alaska Native suggests that the relationship between income and rent is not statistically significant for this group, based on the traditional alpha threshold.</p></li>
</ul>
</section>
<section id="discussion-of-the-model-1" class="level3">
<h3 class="anchored" data-anchor-id="discussion-of-the-model-1">Discussion of the model:</h3>
<ul>
<li>The evident variability in log_INCTOT coefficients across races suggests that the relationship between income and rent is influenced by racial factors, pointing towards the complexity inherent in socio-economic dynamics.</li>
<li>Non-significance in certain racial categories may reflect data limitations or the presence of other variables not captured in the model, indicating areas where further research or data collection could be beneficial.</li>
<li>The model’s overall robustness and the significance of its findings provide valuable insights, yet also suggest that an exploration of additional socio-economic factors and historical trends could contribute to a more nuanced understanding.</li>
</ul>
</section>
</section>
<section id="enhanced-log-log-regression-model-with-interaction-terms-based-on-the-2022-dataset" class="level2">
<h2 class="anchored" data-anchor-id="enhanced-log-log-regression-model-with-interaction-terms-based-on-the-2022-dataset">5. Enhanced Log-Log Regression Model with Interaction Terms (Based on the 2022 Dataset)</h2>
<section id="model-rationale" class="level3">
<h3 class="anchored" data-anchor-id="model-rationale">Model Rationale:</h3>
<ul>
<li>As outlined in Class Blog 4, we’ve built upon the solid foundation established in Section 3. We’re now exploring nonlinearity further and addressing the potential skewness identified in the conclusions of Model 3.</li>
</ul>
</section>
<section id="variable-selection-and-refinement" class="level3">
<h3 class="anchored" data-anchor-id="variable-selection-and-refinement">Variable Selection and Refinement:</h3>
<ul>
<li>The interaction term <code>EMPSTAT * FTOTINC</code> has been introduced to investigate the suspected interaction effect between employment status and total family income.</li>
<li>Post inclusion, the p-value for <code>EMPSTATUnemployed:FTOTINC</code> is slightly above 0.05, suggesting it has borderline statistical significance.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 46%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">5.1113135</td>
<td style="text-align: right;">0.1036114</td>
<td style="text-align: right;">49.3315824</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">log_INCTOT</td>
<td style="text-align: right;">0.1331529</td>
<td style="text-align: right;">0.0073835</td>
<td style="text-align: right;">18.0338588</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ROOMS</td>
<td style="text-align: right;">0.0299321</td>
<td style="text-align: right;">0.0035566</td>
<td style="text-align: right;">8.4158816</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">NFAMS</td>
<td style="text-align: right;">0.0555431</td>
<td style="text-align: right;">0.0098767</td>
<td style="text-align: right;">5.6236800</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AGE</td>
<td style="text-align: right;">-0.0027305</td>
<td style="text-align: right;">0.0005401</td>
<td style="text-align: right;">-5.0552371</td>
<td style="text-align: right;">0.0000004</td>
</tr>
<tr class="even">
<td style="text-align: left;">MARSTMarried, spouse absent</td>
<td style="text-align: right;">0.0941770</td>
<td style="text-align: right;">0.0450879</td>
<td style="text-align: right;">2.0887414</td>
<td style="text-align: right;">0.0367801</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MARSTMarried, spouse present</td>
<td style="text-align: right;">0.1370358</td>
<td style="text-align: right;">0.0230398</td>
<td style="text-align: right;">5.9477787</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">MARSTNever married/single</td>
<td style="text-align: right;">0.0896923</td>
<td style="text-align: right;">0.0234201</td>
<td style="text-align: right;">3.8297086</td>
<td style="text-align: right;">0.0001298</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MARSTSeparated</td>
<td style="text-align: right;">0.0307051</td>
<td style="text-align: right;">0.0434374</td>
<td style="text-align: right;">0.7068820</td>
<td style="text-align: right;">0.4796719</td>
</tr>
<tr class="even">
<td style="text-align: left;">MARSTWidowed</td>
<td style="text-align: right;">0.1049586</td>
<td style="text-align: right;">0.0350501</td>
<td style="text-align: right;">2.9945293</td>
<td style="text-align: right;">0.0027618</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACEBlack/African American</td>
<td style="text-align: right;">0.2465346</td>
<td style="text-align: right;">0.0660208</td>
<td style="text-align: right;">3.7341954</td>
<td style="text-align: right;">0.0001904</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEChinese</td>
<td style="text-align: right;">0.2966334</td>
<td style="text-align: right;">0.0865709</td>
<td style="text-align: right;">3.4264776</td>
<td style="text-align: right;">0.0006163</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACEJapanese</td>
<td style="text-align: right;">0.3086582</td>
<td style="text-align: right;">0.1385602</td>
<td style="text-align: right;">2.2276104</td>
<td style="text-align: right;">0.0259496</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEOther Asian or Pacific Islander</td>
<td style="text-align: right;">0.3309648</td>
<td style="text-align: right;">0.0695640</td>
<td style="text-align: right;">4.7577031</td>
<td style="text-align: right;">0.0000020</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACEOther race, nec</td>
<td style="text-align: right;">0.2729952</td>
<td style="text-align: right;">0.0669648</td>
<td style="text-align: right;">4.0766956</td>
<td style="text-align: right;">0.0000464</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEThree or more major races</td>
<td style="text-align: right;">0.3456014</td>
<td style="text-align: right;">0.0936388</td>
<td style="text-align: right;">3.6907926</td>
<td style="text-align: right;">0.0002259</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACETwo major races</td>
<td style="text-align: right;">0.2766317</td>
<td style="text-align: right;">0.0663374</td>
<td style="text-align: right;">4.1700733</td>
<td style="text-align: right;">0.0000310</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACEWhite</td>
<td style="text-align: right;">0.2627766</td>
<td style="text-align: right;">0.0639610</td>
<td style="text-align: right;">4.1083889</td>
<td style="text-align: right;">0.0000405</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EMPSTATNot in labour force</td>
<td style="text-align: right;">-0.0908464</td>
<td style="text-align: right;">0.0233084</td>
<td style="text-align: right;">-3.8975885</td>
<td style="text-align: right;">0.0000984</td>
</tr>
<tr class="even">
<td style="text-align: left;">EMPSTATUnemployed</td>
<td style="text-align: right;">0.0561573</td>
<td style="text-align: right;">0.0526989</td>
<td style="text-align: right;">1.0656248</td>
<td style="text-align: right;">0.2866433</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FTOTINC</td>
<td style="text-align: right;">0.0000019</td>
<td style="text-align: right;">0.0000001</td>
<td style="text-align: right;">13.5815058</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">REGION_CLASSIFIEDNORTHEAST</td>
<td style="text-align: right;">0.2611149</td>
<td style="text-align: right;">0.0237360</td>
<td style="text-align: right;">11.0007889</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">REGION_CLASSIFIEDSOUTH</td>
<td style="text-align: right;">0.1904665</td>
<td style="text-align: right;">0.0206891</td>
<td style="text-align: right;">9.2061053</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">REGION_CLASSIFIEDWEST</td>
<td style="text-align: right;">0.4456625</td>
<td style="text-align: right;">0.0220563</td>
<td style="text-align: right;">20.2057095</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EMPSTATNot in labour force:FTOTINC</td>
<td style="text-align: right;">0.0000017</td>
<td style="text-align: right;">0.0000003</td>
<td style="text-align: right;">5.3486949</td>
<td style="text-align: right;">0.0000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">EMPSTATUnemployed:FTOTINC</td>
<td style="text-align: right;">0.0000006</td>
<td style="text-align: right;">0.0000010</td>
<td style="text-align: right;">0.6301514</td>
<td style="text-align: right;">0.5286235</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The integration of the interaction term retains the significance of other variables, with no detrimental impact on the model’s variables as reflected in their p-values.</li>
</ul>
</section>
<section id="model-inferences-1" class="level3">
<h3 class="anchored" data-anchor-id="model-inferences-1">Model Inferences:</h3>
<ul>
<li>There is a noticeable shift in the coefficient from 0.1334 to 0.1715199 after adding the interaction term. This change suggests that employment status may moderate the influence of total family income on gross rent. Specifically, a 10% increase in total income (INCTOT) now corresponds to a 17.15% increase in gross rent (RENTGRS), ceteris paribus.</li>
</ul>
</section>
<section id="statistical-performance-assessment-1" class="level3">
<h3 class="anchored" data-anchor-id="statistical-performance-assessment-1">Statistical Performance Assessment:</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.2727009</td>
<td style="text-align: right;">0.2691641</td>
<td style="text-align: right;">0.4920608</td>
<td style="text-align: right;">77.10474</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">-3654.429</td>
<td style="text-align: right;">7362.857</td>
<td style="text-align: right;">7539.709</td>
<td style="text-align: right;">1244.758</td>
<td style="text-align: right;">5141</td>
<td style="text-align: right;">5167</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>All predictors show statistical significance, with the exception of certain categories within marital status and employment status, indicating robustness in the variable selection.</li>
</ul>
</section>
<section id="discussion-of-the-model-2" class="level3">
<h3 class="anchored" data-anchor-id="discussion-of-the-model-2">Discussion of the model:</h3>
<p>-The residual plot suggested an acceptable fit.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>This model also meet all the assumption we discussed in section 3.</li>
</ul>
<p><strong>Therefore, this model’s conclusions offer a credible extension to our understanding of the economic factors influencing rent prices in section 3.</strong></p>
</section>
</section>
</section>
<section id="models-and-inferences-merged-dataset" class="level1">
<h1>Models and Inferences (Merged dataset)</h1>
<section id="outline-1" class="level2">
<h2 class="anchored" data-anchor-id="outline-1">Outline</h2>
<ol type="1">
<li>Log-Log Regression Model by YEAR</li>
<li>Longitudinal Log-Log Regression Model by Race</li>
<li>Time series model</li>
</ol>
</section>
<section id="log-log-regression-model-by-year" class="level2">
<h2 class="anchored" data-anchor-id="log-log-regression-model-by-year">1. Log-Log Regression Model by YEAR</h2>
<section id="model-overview-4" class="level3">
<h3 class="anchored" data-anchor-id="model-overview-4">Model Overview:</h3>
<ul>
<li>This analysis implements the validated Log-Log regression approach on annual data segments to assess temporal trends and variations.</li>
</ul>
</section>
<section id="model-inferences-2" class="level3">
<h3 class="anchored" data-anchor-id="model-inferences-2">Model Inferences:</h3>
<div class="cell">
<div class="cell-output-display">

<div class="datatables html-widget html-fill-item" id="htmlwidget-9f7a038005ff76df4677" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-9f7a038005ff76df4677">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"],[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022],["log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT","log_INCTOT"],[0.1211553170755943,0.1472045803780519,0.1212254194966609,0.1145586252277987,0.117847446418783,0.1206591859669455,0.1210176821919339,0.1313329287431758,0.1130601416480075,0.1176817945127846,0.127902249022881,0.1334457009382962,0.1266135631248069,0.129541853516546,0.1223687846265685,0.1153472955838414,0.1215189252257599,0.1328582940035949,0.1464481488322052,0.1400640832972581,0.1349330572783876,0.1263535174195743,0.1291064652429358],[0.01985220751734872,0.01166675246638406,0.01309746983607714,0.01178742066100236,0.0122843895878077,0.007788165830270418,0.007736133737769704,0.008046142993150948,0.007759946236610075,0.007866817453268428,0.007446802835975973,0.007882719248802841,0.007079976200877931,0.007195595517862768,0.007142445657877201,0.007008651780403832,0.007100125816595436,0.0070752162413777,0.007108114469421251,0.007254449349512482,0.008270535618936429,0.007364535814149777,0.007594047645304567],[6.102863722823646,12.61744266900314,9.255636471308675,9.718718668182069,9.593268397784051,15.49263184638122,15.64317348872808,16.32247013941577,14.56970682536555,14.95926341393512,17.17545795693383,16.92889176010712,17.88333174186469,18.00293710158718,17.13261682174809,16.45784370488373,17.11503829153681,18.77798352318975,20.6029530703561,19.30733492634706,16.31491157228577,17.15702396026185,17.00100806225029],[1.876995190485197e-09,4.67544213178568e-35,6.706284959881171e-20,8.429382497798481e-22,2.91337976996068e-21,1.10636836930901e-52,1.242989838239183e-53,4.099672610527787e-58,5.42190328580662e-47,1.896096040728556e-49,3.22937818434902e-64,1.573151786073291e-62,1.979322784782542e-69,2.775963985706827e-70,4.362938064781562e-64,2.221316414834185e-59,5.771626556098598e-64,2.91226942665766e-76,7.240193281108618e-91,2.590530834891124e-80,5.697809332192453e-58,3.52266179816848e-64,4.147290403703087e-63]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>YEAR<\/th>\n      <th>term<\/th>\n      <th>estimate<\/th>\n      <th>std.error<\/th>\n      <th>statistic<\/th>\n      <th>p.value<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":1,"lengthMenu":[1,5,10,25,50,100],"autoWidth":true,"columnDefs":[{"className":"dt-right","targets":[1,3,4,5,6]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"YEAR","targets":1},{"name":"term","targets":2},{"name":"estimate","targets":3},{"name":"std.error","targets":4},{"name":"statistic","targets":5},{"name":"p.value","targets":6}],"order":[],"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<ul>
<li>The analyses yield detailed <code>log_INCTOT</code> coefficients for each year, elucidating the evolving income-rent relationship dynamics.</li>
<li>Fluctuations in <code>log_INCTOT</code> coefficients over different years suggest changing influences on the dependent variable within the model.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Observations show peaks in coefficient estimates, notably in the early 2000s and around 2020, with subsequent troughs suggesting potential corrective periods.</li>
<li>The coefficient trend exhibits cyclicity with no monotonic progression, featuring multiple peaks and valleys, implying a potential cyclical influence on the income-rent relationship.</li>
<li>Coefficient estimates range within a tight interval, indicating a consistent strength of relationship across the dataset’s timespan.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>R-squared values demonstrate time-bound variability, implying shifts in the model’s explanatory power from year to year.</li>
<li>A recent sharp decline in R-squared highlights a potential reduction in predictive accuracy or a substantial data structure change.</li>
</ul>
</section>
<section id="statistical-performance-assessment-2" class="level3">
<h3 class="anchored" data-anchor-id="statistical-performance-assessment-2">Statistical Performance Assessment:</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 2%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">YEAR</th>
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2000</td>
<td style="text-align: right;">0.3004684</td>
<td style="text-align: right;">0.2734731</td>
<td style="text-align: right;">0.4224935</td>
<td style="text-align: right;">11.13038</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-333.323</td>
<td style="text-align: right;">716.6461</td>
<td style="text-align: right;">827.3891</td>
<td style="text-align: right;">106.3864</td>
<td style="text-align: right;">596</td>
<td style="text-align: right;">620</td>
</tr>
<tr class="even">
<td style="text-align: right;">2001</td>
<td style="text-align: right;">0.2470440</td>
<td style="text-align: right;">0.2375703</td>
<td style="text-align: right;">0.4343406</td>
<td style="text-align: right;">26.07673</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-1071.364</td>
<td style="text-align: right;">2192.7289</td>
<td style="text-align: right;">2330.8294</td>
<td style="text-align: right;">344.8555</td>
<td style="text-align: right;">1828</td>
<td style="text-align: right;">1852</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2002</td>
<td style="text-align: right;">0.2331442</td>
<td style="text-align: right;">0.2219811</td>
<td style="text-align: right;">0.4474190</td>
<td style="text-align: right;">20.88527</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-973.854</td>
<td style="text-align: right;">1997.7081</td>
<td style="text-align: right;">2132.2145</td>
<td style="text-align: right;">316.2903</td>
<td style="text-align: right;">1580</td>
<td style="text-align: right;">1604</td>
</tr>
<tr class="even">
<td style="text-align: right;">2003</td>
<td style="text-align: right;">0.2465441</td>
<td style="text-align: right;">0.2370067</td>
<td style="text-align: right;">0.4480918</td>
<td style="text-align: right;">25.85020</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-1122.311</td>
<td style="text-align: right;">2294.6224</td>
<td style="text-align: right;">2432.5740</td>
<td style="text-align: right;">364.8287</td>
<td style="text-align: right;">1817</td>
<td style="text-align: right;">1841</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2004</td>
<td style="text-align: right;">0.2503521</td>
<td style="text-align: right;">0.2402157</td>
<td style="text-align: right;">0.4474393</td>
<td style="text-align: right;">24.69849</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-1048.315</td>
<td style="text-align: right;">2146.6299</td>
<td style="text-align: right;">2282.9544</td>
<td style="text-align: right;">340.5435</td>
<td style="text-align: right;">1701</td>
<td style="text-align: right;">1725</td>
</tr>
<tr class="even">
<td style="text-align: right;">2005</td>
<td style="text-align: right;">0.2578132</td>
<td style="text-align: right;">0.2537284</td>
<td style="text-align: right;">0.4519094</td>
<td style="text-align: right;">63.11557</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-2613.433</td>
<td style="text-align: right;">5276.8654</td>
<td style="text-align: right;">5435.4542</td>
<td style="text-align: right;">853.4443</td>
<td style="text-align: right;">4179</td>
<td style="text-align: right;">4203</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2006</td>
<td style="text-align: right;">0.2886511</td>
<td style="text-align: right;">0.2846915</td>
<td style="text-align: right;">0.4463248</td>
<td style="text-align: right;">72.89924</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-2532.394</td>
<td style="text-align: right;">5114.7885</td>
<td style="text-align: right;">5273.0962</td>
<td style="text-align: right;">823.1186</td>
<td style="text-align: right;">4132</td>
<td style="text-align: right;">4156</td>
</tr>
<tr class="even">
<td style="text-align: right;">2007</td>
<td style="text-align: right;">0.2579863</td>
<td style="text-align: right;">0.2539132</td>
<td style="text-align: right;">0.4657137</td>
<td style="text-align: right;">63.33896</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-2747.100</td>
<td style="text-align: right;">5544.2009</td>
<td style="text-align: right;">5702.8551</td>
<td style="text-align: right;">908.7660</td>
<td style="text-align: right;">4190</td>
<td style="text-align: right;">4214</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2008</td>
<td style="text-align: right;">0.2473125</td>
<td style="text-align: right;">0.2433582</td>
<td style="text-align: right;">0.4633991</td>
<td style="text-align: right;">62.54309</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-2848.263</td>
<td style="text-align: right;">5746.5269</td>
<td style="text-align: right;">5906.2723</td>
<td style="text-align: right;">940.1263</td>
<td style="text-align: right;">4378</td>
<td style="text-align: right;">4402</td>
</tr>
<tr class="even">
<td style="text-align: right;">2009</td>
<td style="text-align: right;">0.2549819</td>
<td style="text-align: right;">0.2512881</td>
<td style="text-align: right;">0.4705660</td>
<td style="text-align: right;">69.03019</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3089.421</td>
<td style="text-align: right;">6228.8423</td>
<td style="text-align: right;">6390.0277</td>
<td style="text-align: right;">1027.2247</td>
<td style="text-align: right;">4639</td>
<td style="text-align: right;">4663</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2010</td>
<td style="text-align: right;">0.2679043</td>
<td style="text-align: right;">0.2644022</td>
<td style="text-align: right;">0.4511145</td>
<td style="text-align: right;">76.49772</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-2997.845</td>
<td style="text-align: right;">6045.6891</td>
<td style="text-align: right;">6207.7645</td>
<td style="text-align: right;">978.4487</td>
<td style="text-align: right;">4808</td>
<td style="text-align: right;">4832</td>
</tr>
<tr class="even">
<td style="text-align: right;">2011</td>
<td style="text-align: right;">0.2603548</td>
<td style="text-align: right;">0.2568985</td>
<td style="text-align: right;">0.4740125</td>
<td style="text-align: right;">75.32791</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3313.745</td>
<td style="text-align: right;">6677.4909</td>
<td style="text-align: right;">6840.1493</td>
<td style="text-align: right;">1105.9138</td>
<td style="text-align: right;">4922</td>
<td style="text-align: right;">4946</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2012</td>
<td style="text-align: right;">0.2771554</td>
<td style="text-align: right;">0.2739096</td>
<td style="text-align: right;">0.4600769</td>
<td style="text-align: right;">85.38670</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3294.673</td>
<td style="text-align: right;">6639.3453</td>
<td style="text-align: right;">6802.9947</td>
<td style="text-align: right;">1084.1776</td>
<td style="text-align: right;">5122</td>
<td style="text-align: right;">5146</td>
</tr>
<tr class="even">
<td style="text-align: right;">2013</td>
<td style="text-align: right;">0.2761514</td>
<td style="text-align: right;">0.2728593</td>
<td style="text-align: right;">0.4602770</td>
<td style="text-align: right;">83.88121</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3255.114</td>
<td style="text-align: right;">6560.2281</td>
<td style="text-align: right;">6723.5597</td>
<td style="text-align: right;">1071.3503</td>
<td style="text-align: right;">5057</td>
<td style="text-align: right;">5081</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2014</td>
<td style="text-align: right;">0.2739684</td>
<td style="text-align: right;">0.2708225</td>
<td style="text-align: right;">0.4612843</td>
<td style="text-align: right;">87.08596</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3428.168</td>
<td style="text-align: right;">6906.3364</td>
<td style="text-align: right;">7070.8734</td>
<td style="text-align: right;">1129.4535</td>
<td style="text-align: right;">5308</td>
<td style="text-align: right;">5332</td>
</tr>
<tr class="even">
<td style="text-align: right;">2015</td>
<td style="text-align: right;">0.2676026</td>
<td style="text-align: right;">0.2643909</td>
<td style="text-align: right;">0.4591722</td>
<td style="text-align: right;">83.32228</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3363.339</td>
<td style="text-align: right;">6776.6777</td>
<td style="text-align: right;">6940.9176</td>
<td style="text-align: right;">1105.8510</td>
<td style="text-align: right;">5245</td>
<td style="text-align: right;">5269</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2016</td>
<td style="text-align: right;">0.2617749</td>
<td style="text-align: right;">0.2585815</td>
<td style="text-align: right;">0.4688414</td>
<td style="text-align: right;">81.97435</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3520.766</td>
<td style="text-align: right;">7091.5316</td>
<td style="text-align: right;">7256.1108</td>
<td style="text-align: right;">1168.7418</td>
<td style="text-align: right;">5317</td>
<td style="text-align: right;">5341</td>
</tr>
<tr class="even">
<td style="text-align: right;">2017</td>
<td style="text-align: right;">0.2588462</td>
<td style="text-align: right;">0.2556947</td>
<td style="text-align: right;">0.4728262</td>
<td style="text-align: right;">82.13395</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3627.601</td>
<td style="text-align: right;">7305.2017</td>
<td style="text-align: right;">7470.2079</td>
<td style="text-align: right;">1209.2611</td>
<td style="text-align: right;">5409</td>
<td style="text-align: right;">5433</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2018</td>
<td style="text-align: right;">0.2877600</td>
<td style="text-align: right;">0.2847376</td>
<td style="text-align: right;">0.4738139</td>
<td style="text-align: right;">95.20847</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3646.330</td>
<td style="text-align: right;">7342.6610</td>
<td style="text-align: right;">7507.7177</td>
<td style="text-align: right;">1216.7881</td>
<td style="text-align: right;">5420</td>
<td style="text-align: right;">5444</td>
</tr>
<tr class="even">
<td style="text-align: right;">2019</td>
<td style="text-align: right;">0.2898507</td>
<td style="text-align: right;">0.2867566</td>
<td style="text-align: right;">0.4801230</td>
<td style="text-align: right;">93.68034</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3621.724</td>
<td style="text-align: right;">7293.4472</td>
<td style="text-align: right;">7457.8479</td>
<td style="text-align: right;">1216.9048</td>
<td style="text-align: right;">5279</td>
<td style="text-align: right;">5303</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">0.2820342</td>
<td style="text-align: right;">0.2778789</td>
<td style="text-align: right;">0.4948471</td>
<td style="text-align: right;">67.87314</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-2848.262</td>
<td style="text-align: right;">5746.5231</td>
<td style="text-align: right;">5903.8619</td>
<td style="text-align: right;">973.1280</td>
<td style="text-align: right;">3974</td>
<td style="text-align: right;">3998</td>
</tr>
<tr class="even">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">0.2677132</td>
<td style="text-align: right;">0.2643873</td>
<td style="text-align: right;">0.4841706</td>
<td style="text-align: right;">80.49233</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3517.113</td>
<td style="text-align: right;">7084.2259</td>
<td style="text-align: right;">7247.5919</td>
<td style="text-align: right;">1187.1087</td>
<td style="text-align: right;">5064</td>
<td style="text-align: right;">5088</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">0.2239915</td>
<td style="text-align: right;">0.2205238</td>
<td style="text-align: right;">0.5099087</td>
<td style="text-align: right;">64.59389</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-3842.513</td>
<td style="text-align: right;">7735.0255</td>
<td style="text-align: right;">7898.7961</td>
<td style="text-align: right;">1338.2554</td>
<td style="text-align: right;">5147</td>
<td style="text-align: right;">5171</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>All model coefficients are statistically validated, with a noticeable exception in the MARSTSeparated category for the year 2022.</li>
<li>R-squared values exhibit minor fluctuations over time, signifying a stable degree of explained variability in the response variable by the model.</li>
<li>Adjusted R-squared values, marginally lower than the R-squared, adhere to expectations, considering model complexity relative to data volume.</li>
<li>P-values indicate consistent statistical significance for the model’s predictors on an annual basis.</li>
<li>Log-likelihood, AIC, and BIC values increment over time, which may indicate an improving model fit or increasing data variability.</li>
<li>The trends in model deviance require additional context for clear interpretation, while a gradual decrease in df.residual suggests either an increase in model parameters or variations in data availability over time.</li>
</ul>
</section>
</section>
<section id="longitudinal-log-log-regression-model-by-race" class="level2">
<h2 class="anchored" data-anchor-id="longitudinal-log-log-regression-model-by-race">2. Longitudinal Log-Log Regression Model by Race</h2>
<section id="model-overview-5" class="level3">
<h3 class="anchored" data-anchor-id="model-overview-5">Model Overview:</h3>
<ul>
<li>This model extended the 2022 dataset analysis to explore how the rent-income relationship for each racial group has evolved from 2000 to 2022.</li>
<li>Trends over time for each race were charted to illustrate these dynamics.</li>
<li>Similar to the 2022 model, the coefficients were found to be statistically significant and the residual plots falling within an acceptable range.</li>
</ul>
</section>
<section id="model-inferences-3" class="level3">
<h3 class="anchored" data-anchor-id="model-inferences-3">Model Inferences:</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 16%">
<col style="width: 9%">
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">YEAR</th>
<th style="text-align: right;">coef_American Indian or Alaska Native</th>
<th style="text-align: right;">coef_Black/African American</th>
<th style="text-align: right;">coef_Chinese</th>
<th style="text-align: right;">coef_Japanese</th>
<th style="text-align: right;">coef_Other Asian or Pacific Islander</th>
<th style="text-align: right;">coef_Other race, nec</th>
<th style="text-align: right;">coef_Three or more major races</th>
<th style="text-align: right;">coef_Two major races</th>
<th style="text-align: right;">coef_White</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2001</td>
<td style="text-align: right;">0.0044494</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0097707</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1221862</td>
<td style="text-align: right;">0.0818381</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1007001</td>
<td style="text-align: right;">0.1445229</td>
</tr>
<tr class="even">
<td style="text-align: right;">2005</td>
<td style="text-align: right;">-0.1728914</td>
<td style="text-align: right;">0.0873527</td>
<td style="text-align: right;">0.1326179</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0897322</td>
<td style="text-align: right;">0.0429701</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1379574</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2007</td>
<td style="text-align: right;">0.1239418</td>
<td style="text-align: right;">0.1115806</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0864570</td>
<td style="text-align: right;">0.1019018</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0988822</td>
<td style="text-align: right;">0.1401784</td>
</tr>
<tr class="even">
<td style="text-align: right;">2008</td>
<td style="text-align: right;">0.1662273</td>
<td style="text-align: right;">0.0717442</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0495650</td>
<td style="text-align: right;">0.0811385</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0705536</td>
<td style="text-align: right;">0.1261771</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2009</td>
<td style="text-align: right;">-0.0290841</td>
<td style="text-align: right;">0.0982650</td>
<td style="text-align: right;">0.0462740</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0979882</td>
<td style="text-align: right;">0.1357880</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0883666</td>
<td style="text-align: right;">0.1215903</td>
</tr>
<tr class="even">
<td style="text-align: right;">2011</td>
<td style="text-align: right;">-0.0246266</td>
<td style="text-align: right;">0.1289264</td>
<td style="text-align: right;">0.1080701</td>
<td style="text-align: right;">-0.3049829</td>
<td style="text-align: right;">0.1056626</td>
<td style="text-align: right;">0.0704745</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0950769</td>
<td style="text-align: right;">0.1434630</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2012</td>
<td style="text-align: right;">0.0829896</td>
<td style="text-align: right;">0.0815911</td>
<td style="text-align: right;">0.1408589</td>
<td style="text-align: right;">0.2402733</td>
<td style="text-align: right;">0.0947194</td>
<td style="text-align: right;">0.0336927</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0447647</td>
<td style="text-align: right;">0.1477391</td>
</tr>
<tr class="even">
<td style="text-align: right;">2013</td>
<td style="text-align: right;">0.1450099</td>
<td style="text-align: right;">0.1208850</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.3074672</td>
<td style="text-align: right;">0.0719337</td>
<td style="text-align: right;">0.0944647</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1077284</td>
<td style="text-align: right;">0.1413223</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2014</td>
<td style="text-align: right;">-0.0806190</td>
<td style="text-align: right;">0.0774011</td>
<td style="text-align: right;">0.1243816</td>
<td style="text-align: right;">0.1948937</td>
<td style="text-align: right;">0.1704745</td>
<td style="text-align: right;">0.0192973</td>
<td style="text-align: right;">-0.0246775</td>
<td style="text-align: right;">0.0501507</td>
<td style="text-align: right;">0.1423022</td>
</tr>
<tr class="even">
<td style="text-align: right;">2015</td>
<td style="text-align: right;">0.2288886</td>
<td style="text-align: right;">0.0866523</td>
<td style="text-align: right;">0.1437636</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0588220</td>
<td style="text-align: right;">0.0124419</td>
<td style="text-align: right;">-0.0798592</td>
<td style="text-align: right;">0.0240695</td>
<td style="text-align: right;">0.1366126</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2016</td>
<td style="text-align: right;">0.0724100</td>
<td style="text-align: right;">0.1070357</td>
<td style="text-align: right;">0.0935354</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0892159</td>
<td style="text-align: right;">0.0831495</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1105840</td>
<td style="text-align: right;">0.1281357</td>
</tr>
<tr class="even">
<td style="text-align: right;">2017</td>
<td style="text-align: right;">0.1140436</td>
<td style="text-align: right;">0.1154084</td>
<td style="text-align: right;">0.0120262</td>
<td style="text-align: right;">0.0758910</td>
<td style="text-align: right;">0.0610027</td>
<td style="text-align: right;">0.1443399</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0379656</td>
<td style="text-align: right;">0.1514833</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2018</td>
<td style="text-align: right;">0.1443089</td>
<td style="text-align: right;">0.1216139</td>
<td style="text-align: right;">0.2833792</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1070153</td>
<td style="text-align: right;">0.0425257</td>
<td style="text-align: right;">0.3835364</td>
<td style="text-align: right;">0.1375949</td>
<td style="text-align: right;">0.1594088</td>
</tr>
<tr class="even">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">0.0264148</td>
<td style="text-align: right;">0.0821522</td>
<td style="text-align: right;">0.0947932</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1345643</td>
<td style="text-align: right;">0.1008466</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0531118</td>
<td style="text-align: right;">0.1628788</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">-0.0599569</td>
<td style="text-align: right;">0.0664240</td>
<td style="text-align: right;">0.1149156</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1242797</td>
<td style="text-align: right;">0.0334209</td>
<td style="text-align: right;">-0.0382770</td>
<td style="text-align: right;">0.0856113</td>
<td style="text-align: right;">0.1649109</td>
</tr>
<tr class="even">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">0.0984965</td>
<td style="text-align: right;">0.0632937</td>
<td style="text-align: right;">0.2196783</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1033151</td>
<td style="text-align: right;">0.0390094</td>
<td style="text-align: right;">0.0722550</td>
<td style="text-align: right;">0.0800541</td>
<td style="text-align: right;">0.1637250</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0358345</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1459856</td>
</tr>
<tr class="even">
<td style="text-align: right;">2002</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0994888</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1131498</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1290758</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2003</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1201889</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0611945</td>
<td style="text-align: right;">0.0426896</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.0781177</td>
<td style="text-align: right;">0.1278780</td>
</tr>
<tr class="even">
<td style="text-align: right;">2004</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1245230</td>
<td style="text-align: right;">0.0048313</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0655594</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0013052</td>
<td style="text-align: right;">0.1292762</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2006</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1192481</td>
<td style="text-align: right;">0.0993890</td>
<td style="text-align: right;">0.4505390</td>
<td style="text-align: right;">0.1058852</td>
<td style="text-align: right;">0.0840827</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1273188</td>
</tr>
<tr class="even">
<td style="text-align: right;">2010</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0965021</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.8670287</td>
<td style="text-align: right;">0.1104422</td>
<td style="text-align: right;">0.0597122</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0686506</td>
<td style="text-align: right;">0.1432963</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2019</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1027066</td>
<td style="text-align: right;">0.2814538</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1331487</td>
<td style="text-align: right;">0.0892457</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1464698</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>Specific Trends:</li>
</ul>
<p><strong>Alaska Native</strong>: Shows minor fluctuations around zero, with both positive and negative coefficients, indicating inconsistent trends over the years.</p>
<p><strong>American</strong>: This category has NA values, suggesting incomplete data, making it hard to discern a clear trend.</p>
<p><strong>Chinese</strong>: Generally has higher positive coefficients compared to other groups, particularly noticeable in later years, indicating a strong positive association with income in those years.</p>
<p><strong>Japanese</strong>: Has some missing values but otherwise presents mostly positive coefficients, with a notable spike in recent years.</p>
<p><strong>Islander</strong>: Also features both positive and negative coefficients with considerable variability.</p>
<p><strong>Other race, nec</strong>: Shows a mix of positive, negative, and NA values, making a clear trend difficult to establish.</p>
<p><strong>Two or more races</strong>: This group generally has positive coefficients, with a few exceptions, suggesting a fairly consistent positive association with income.</p>
<p><strong>Whites</strong>: Present a range of coefficients, mostly positive with some fluctuations, but generally indicate a positive association with income.</p>
<ul>
<li>Race Comparisons: Certain racial categories, like those identifying as Chinese and Japanese, tend to have higher coefficients, suggesting a stronger relationship with income than other races in the dataset. Conversely, the ‘Other race, nec’ category often has lower coefficients, implying a weaker association with income.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-25-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-25-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-25-5.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-25-6.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-25-7.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-25-8.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-25-9.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="statistical-performance-2" class="level3">
<h3 class="anchored" data-anchor-id="statistical-performance-2">Statistical Performance:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>log_inctot_p_values <span class="ot">&lt;-</span> data_twenty_filtered_final <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(RACE, YEAR) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">do</span>({</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    model <span class="ot">=</span> <span class="fu">lm</span>(log_RENTGRS <span class="sc">~</span> log_INCTOT <span class="sc">+</span> KITCHEN <span class="sc">+</span> ROOMS <span class="sc">+</span> NFAMS <span class="sc">+</span> AGE <span class="sc">+</span> MARST <span class="sc">+</span> EMPSTAT <span class="sc">+</span> REGION_CLASSIFIED, <span class="at">data =</span> .)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>(model)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  }) <span class="sc">%&gt;%</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"log_INCTOT"</span>) <span class="sc">%&gt;%</span>  <span class="co"># Filter to only include rows where the term is 'log_INCTOT'</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(RACE, YEAR, term, estimate, p.value)  <span class="co"># Select only the relevant columns</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print or view the results</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(log_inctot_p_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 149 × 5
   RACE                              YEAR term       estimate p.value
   &lt;chr&gt;                            &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt;   &lt;dbl&gt;
 1 American Indian or Alaska Native  2001 log_INCTOT  0.00445  0.983 
 2 American Indian or Alaska Native  2005 log_INCTOT -0.173    0.0485
 3 American Indian or Alaska Native  2007 log_INCTOT  0.124    0.265 
 4 American Indian or Alaska Native  2008 log_INCTOT  0.166    0.0480
 5 American Indian or Alaska Native  2009 log_INCTOT -0.0291   0.779 
 6 American Indian or Alaska Native  2011 log_INCTOT -0.0246   0.835 
 7 American Indian or Alaska Native  2012 log_INCTOT  0.0830   0.154 
 8 American Indian or Alaska Native  2013 log_INCTOT  0.145    0.0679
 9 American Indian or Alaska Native  2014 log_INCTOT -0.0806   0.455 
10 American Indian or Alaska Native  2015 log_INCTOT  0.229    0.0149
# ℹ 139 more rows</code></pre>
</div>
</div>
<ul>
<li>All showed to be statistically significant ### Discussion of the topic: Race is really a point that needs to explore. Thorugh the result and the visualization of the coefficient changes for each race, there is defintely different pattens showed.</li>
</ul>
</section>
</section>
<section id="time-series-model" class="level2">
<h2 class="anchored" data-anchor-id="time-series-model">3.Time series model</h2>
<hr>
</section>
<section id="rubric-on-this-page" class="level2">
<h2 class="anchored" data-anchor-id="rubric-on-this-page">Rubric: On this page</h2>
<p>You will</p>
<ul>
<li>Introduce what motivates your Data Analysis (DA)
<ul>
<li>Which variables and relationships are you most interested in?</li>
<li>What questions are you interested in answering?</li>
<li>Provide context for the rest of the page. This will include figures/tables that illustrate aspects of the data of your question.</li>
</ul></li>
<li>Modeling and Inference
<ul>
<li>The page will include some kind of formal statistical model. This could be a linear regression, logistic regression, or another modeling framework.</li>
<li>Explain the ideas and techniques you used to choose the predictors for your model. (Think about including interaction terms and other transformations of your variables.)</li>
<li>Describe the results of your modelling and make sure to give a sense of the uncertainty in your estimates and conclusions.</li>
</ul></li>
<li>Explain the flaws and limitations of your analysis
<ul>
<li>Are there some assumptions that you needed to make that might not hold? Is there other data that would help to answer your questions?</li>
</ul></li>
<li>Clarity Figures
<ul>
<li>Are your figures/tables/results easy to read, informative, without problems like overplotting, hard-to-read labels, etc?</li>
<li>Each figure should provide a key insight. Too many figures or other data summaries can detract from this. (While not a hard limit, around 5 total figures is probably a good target.)</li>
<li>Default <code>lm</code> output and plots are typically not acceptable.</li>
</ul></li>
<li>Clarity of Explanations
<ul>
<li>How well do you explain each figure/result?</li>
<li>Do you provide interpretations that suggest further analysis or explanations for observed phenomenon?</li>
</ul></li>
<li>Organization and cleanliness.
<ul>
<li>Make sure to remove excessive warnings, hide most or all code, organize with sections or multiple pages, use bullets, etc.</li>
<li>This page should be self-contained, i.e.&nbsp;provide a description of the relevant data.</li>
</ul></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>