---
title: Data
description: We describe the sources of our data and the cleaning process.
toc: true
draft: false
---
## Describe where/how to find data.
Our dataset comes from [IPUMS USA](https://usa.ipums.org/usa/index.shtml).  

The original data of this website came from censuses as well as the American Community Surveys (ACS) that began in 2000 and are still going on today. We chose our dataset from this website IPUMS because this website contains datasets that are large, valid and complex, containing detailed microdata, which aims to facilitate transformative research, education, and policy-making by aggregating data across times and places. It makes the datasets on this website very appropriate for our research to streamline our analysis of changes, data merging, and comparative research.
  
  
## Describe the different data files used and what each variable means.

### Table contains all the variables we have
We have highlighted all key dependent variables (RENTGRS) and independent variables (INCTOT) in bold.

| Variable | Description                       |
|----------|-----------------------------------|
| PROPINSR | Annual property insurance cost    |
| **RENTGRS** | Monthly gross rent                |
| COSTGAS   | Annual gas cost                   |
| COSTWATR  | Annual water cost                 |
| HHINCOME  | Total household income            |
| KITCHEN   | Kitchen or cooking facilities     |
| ROOMS     | Number of rooms                   |
| BEDROOMS  | Number of bedrooms                |
| NFAMS     | Number of families in household   |
| AGE       | Age                               |
| MARST     | Marital status                    |
| RACE      | Race           |
|**INCTOT** | Total personal income             |
| FTOTINC   | Total family income               |
| POVERTY   | Poverty status                    |


## Describe any cleaning you had to do for your data.
- Here is the link to our cleaned dataset [cleaned dataset.](./dataset//rent_income.rds)

- For our dependent variable—rent—we exclude records indicating a rent of 0. This exclusion is based on the understanding that a 0 rent suggests the individual owns their home or lives in a situation not pertinent to our target research population, which is individuals who rent their housing.

- Exclude data entries characterized by specific codes indicative of missing or unknown values, as well as those representing values deemed inappropriate for analytical purposes. The following table shows the variables we processed:
* Given the vast size of the original dataset, which includes millions of records, we opted to remove these entries directly. This decision does not compromise our ability to conduct a thorough analysis, as the remaining dataset is still large and clean enough for reliable and robust research conclusions.

| Variable     | Description                     | Notes                                                                                                   |
|---------------|--------------------|-------------------------------------|
| **INCTOT**   | Total personal income           | Specific codes detailed below:                                                                          |
|              |                                 | 0000001 = \$1 or break even (2000, 2005-onward ACS and PRCS)                                            |
|              |                                 | 9999999 = N/A                                                                                           |
|              |                                 | 9999998 = Unknown                                                                                       |
| **FTOTINC**  | Total family income             | Specific codes detailed below:                                                                          |
|              |                                 | -000001 = Net loss (1950)                                                                               |
|              |                                 | 9999998 = Not ascertained (1950)                                                                        |
|              |                                 | 9999999 = N/A                                                                                           |
| **COSTGAS**  | Annual gas cost                 | Specific codes detailed below:                                                                          |
|              |                                 | 0000 = N/A                                                                                              |
|              |                                 | 0002 = \$1 or \$2 (2000)                                                                                |
|              |                                 | 9992 = Included in electricity payment (2003-onward ACS/PRCS)                                           |
|              |                                 | 9993 = No charge or no gas used (1990, 2000, 2003-onward ACS/PRCS)                                      |
|              |                                 | 9994 = Gas not used (1970, 1980)                                                                        |
|              |                                 | 9995 = Gas included in rent or no charge (1980)                                                         |
|              |                                 | 9996 = Gas included in rent (1970)                                                                      |
|              |                                 | 9997 = Gas included in rent or in condo fee (1990, 2000, 2003-onward ACS/PRCS)                          |
|              |                                 | 9998 = No charge, none used, or gas included in rent, condo fee, or electricity payment (2000-2002 ACS) |
| **COSTWATR** | Annual water cost               | Specific codes detailed below:                                                                          |
|              |                                 | 0000 = N/A                                                                                              |
|              |                                 | 0002 = \$1 or \$2 (2000)                                                                                |
|              |                                 | 9993 = No charge or no used (1990, 2000, 2003-onward ACS/PRCS)                                          |
|              |                                 | 9995 = Water included in rent or no charge (1970, 1980)                                                 |
|              |                                 | 9997 = Water included in rent or in condo fee (1990, 2000, 2003-onward ACS/PRCS)                        |
|              |                                 | 9998 = No charge, none used, or water included in rent or condo fee (2000-2002 ACS)                     |
| **KITCHEN**  | Kitchen or cooking facilities   | 0 = N/A                                                                                                 |
| **ROOMS**    | Number of rooms                 | 00 = N/A                                                                                                |                                                            |
| **POVERTY**  | Poverty status                  | 000 = N/A                                                                                               |

- Recode certain variables. We modified certain variables in the dataset that are encoded with specific numerical codes, which reflect categories or qualitative information rather than quantitative values.
The following table:
The table below summarizes all variables that possess this characteristic:

| Variable   | Description                                | Notes                                                             |
|------------|--------------------------------------------|-------------------------------------------------------------------|
| **INCTOT**     | Total personal income                      | Specific codes detailed below:                                    |
|            |                                            | -009995 = -$9,900 (1980)                                           |
|            |                                            | -000001 = Net loss (1950)                                          |
|            |                                            | FTOTINC-000001 = Net loss (1950)                                   |
| **KITCHEN**    | Kitchen facilities                         | 0 = N/A                                                            |
|            |                                            | 1 = No                                                            |
|            |                                            | 2 = No, or shared use                                              |
|            |                                            | 3 = Yes, shared use                                                |
|            |                                            | 4 = Yes (shared or exclusive use)                                  |
|            |                                            | 5 = Yes, exclusive use                                             |
| **MARST**      | Marital status                             | 1 = Married, spouse present                                        |
|            |                                            | 2 = Married, spouse absent                                         |
|            |                                            | 3 = Separated                                                      |
|            |                                            | 4 = Divorced                                                       |
|            |                                            | 5 = Widowed                                                        |
|            |                                            | 6 = Never married/single                                           |
|            |                                            | 9 = Blank, missing                                                 |
| **RACE**       | Race                                       | 1 = White                                                          |
|            |                                            | 2 = Black/African American                                         |
|            |                                            | 3 = American Indian or Alaska Native                               |
|            |                                            | 4 = Chinese                                                        |
|            |                                            | 5 = Japanese                                                       |
|            |                                            | 6 = Other Asian or Pacific Islander                                |
|            |                                            | 7 = Other race, nec                                                |
|            |                                            | 8 = Two major races                                                |
|            |                                            | 9 = Three or more major races                                      |
| **RACED**      | Detailed Race                              | 1 = White                                                          |
|            |                                            | 2 = Black/African American                                         |
|            |                                            | 3 = American Indian or Alaska Native                               |
|            |                                            | 4 = Chinese                                                        |
|            |                                            | 5 = Japanese                                                       |
|            |                                            | 6 = Other Asian or Pacific Islander                                |
|            |                                            | 7 = Other race, nec                                                |
|            |                                            | 8 = Two major races                                                |
|            |                                            | 9 = Three or more major races                                      |
| **POVERTY**    | Poverty levels                             | 001 = 1 percent or less of poverty threshold (including 0 or negative income) |
|            |                                            | 501 = 501 percent or more of poverty threshold                     |

- The original data source provided datasets for specific years, not in a continuous sequence. Our primary focus was on the latest data from 2022 for initial research. However, we plan to expand our analysis by incorporating data from 2019 and other years, allowing for comparative studies across different years.

### Summary of numerical variables we have right now 
```{r}
library(dplyr)
library(tidyr)
library(here)
data_path <- here("dataset", "rent_income.csv")
library(readr)
rent_data <- read_csv(data_path,show_col_types = FALSE)
summary_data <- rent_data %>%
  summarise(across(c(RENTGRS, COSTGAS, COSTWATR, ROOMS, AGE, FTOTINC, POVERTY),
                   list(Mean = ~mean(.x),
                        Median = ~median(.x),
                        Min = ~min(.x),
                        Max = ~max(.x)),
                   .names = "{.col}_{.fn}")) %>%
  pivot_longer(cols = everything(),
               names_to = "summary",
               values_to = "value") %>%
  separate(summary, into = c("variable", "statistic"), sep = "_") %>%
  pivot_wider(names_from = "statistic", values_from = "value") %>%
  select(variable, Mean, Median, Min, Max)
print(summary_data)
```


  