---
title: "Class Blog 1"
subtitle: "Three datasets proposed for final project"
author: "Yating Zhu,Dingyu Guo,Suh Edwin Jiho"
date: "2024-03-03"
date-modified: "2024-03-03"
draft: FALSE
---
# Dataset 1: Rent Analysis

## Key Questions we want to explore 
The primary objective is to explore the relationship between rent and personal total income. And other questions can also be answered like: Are there significant differences in rent burdens across different race groups or geographical locations? How do factors like age, employment status, and family size influence this relationship? 

## Introduction
The dataset under investigation is sourced from IPUMS USA, a reputable platform that aggregates data collected through the U.S. Census and American Community Surveys (ACS).
Our dataset is particularly focused on the year 2022. This website also includes data from other years, facilitating for further time-series analysis if needed. The dataset is substantial, containing 1,000,000 rows and 26 columns. The data can be grouped by various categories for detailed analysis and identifying trends. This dataset contains both numerical and categorical variables. Numerical variables include age, poverty level, total personal income, number of family members in households, and family income, among others. Categorical variables encompass sex, marital status, employment status, elevator and flush toilet availability, race, etc. One of the main challenges anticipated with this dataset is the presence of missing values, which could complicate data cleaning processes and affect the data size and quality. However, given the dataset's large size, it remains feasible to extract a substantial sample (over 10,000 records) for robust analysis.

## Link 
[IPUMS USA website](https://usa.ipums.org/usa/index.shtml)

[A PDF containing screenshots of the selected variables on the IPUMS HEALTH SURVEY website](https://drive.google.com/file/d/1QKT4GWGYHTPB-t6anUsxq9LmeD2_OsPb/view?usp=sharing)

*Through these variables names, look for the corresponding variable name in the first link and you see the specific description of each variable. But IPUMS cannot distribute users' selected datasets' information directly to others.

# Dataset 2: Diabetes Problem 

## Key Questions we want to explore 
The main question we want to focus based on this dataset is the relationship between the age of diabetes diagnosis and personal income. And we can also explore other questions related to this topics like how socioeconomic status influences health outcomes, the patients’ current status and other related.

## Introduction
This dataset is derived from IPUMS Health Surveys. The sources are from the reputable institutions including The Eunice Kennedy Shriver National Institute of Child Health and Human Development, Stat/Transfer, State Health Access Data Assistance Center, and the University of Minnesota, underscoring its credibility. The primary data are derived from the National Health Interview Survey (NHIS) and the Medical Expenditure Panel Survey (MEPS), which collectively offer a rich and comprehensive dataset representative of the U.S. population. This dataset includes a wide range of variables, both numerical and categorical. Numerical variables cover aspects such as the age of diabetes diagnosis, household weight, family income, educational attainment, poverty level, enrollment fees or premiums for Medicaid plans and etc. Categorical variables include race, insurance coverage, diabetic pill consumption, types of diabetes and etc. The dataset’s size is large, containing over 10,000,000 columns and 24 rows.  The dataset's compatibility can allow us to use dplyr, forcats, lubridate and other skills as we learnt in this class to manipulate and visualize, which makes it an excellent resource for applying and expanding upon the analytical skills developed in class. However, several challenges are anticipated in working with this dataset. One issue is the data was not from these two years. This could limit the accuracy of attributing findings to current conditions. Additionally, there are soma self-reported answers in this dataset, which introduces potential biases. But wee think the large sample size may mitigate the impact of individual errors or biases. Technical challenges may arise during the data analysis, particularly in categorizing and analyzing diverse groups within the dataset.

## Link 
[IPUMS HEALTH SURVEY website](https://healthsurveys.ipums.org/)

[A PDF containing screenshots of the selected variables on the IPUMS HEALTH SURVEY website](https://drive.google.com/file/d/1QKT4GWGYHTPB-t6anUsxq9LmeD2_OsPb/view?usp=sharing)


# Dataset 3: Education

## Key Questions we want to explore 
The main questions we aimed to address in this dataset involve predicting income levels based on the influence of education. Other variables like work class, and hours worked per week on income, and races can also be used to classify different groups and identify demographic patterns related to income disparities .

## Introduction
This dataset comes from  1994 Census bureau database, which is very reliable data source. It comprises 32,561 rows and 15 columns, and the columns represent various attributes such as age, work class, final weight (fnlwgt), education level, marital status, occupation, relationship, race, sex, capital gain, capital loss, hours per week worked, native country, and income. Challenges in analyzing this dataset may include handling missing data (especially in the 'workclass' and 'occupation' columns where "?" is noted) and how to classify and interpret this. 

## Link 
[The Kaggle link](https://www.kaggle.com/datasets/uciml/adult-census-income) 

[The original dataset comes from the U.S. Census Bureau](https://www.census.gov/en.html)

