{
  "hash": "1a28fe768b25e97e89a5bc76785b0135",
  "result": {
    "markdown": "---\ntitle: \"Class blog 6\"\nauthor: \"Yating Zhu\"\ndate: \"2024-04-17\"\ndate-modified: \"2024-04-17\"\ndraft: FALSE\n---\n\n::: {.cell}\n\n:::\n\n## Group BY Race, see coefficients changes over years and races\n\n### Year 2022\n- Confirmed that RACE is a factor and has at least two levels. \n\n::: {.cell}\n\n:::\n\n- Identifying and removing groups where any of the specified categorical variables have only one level within each racial category, potentially indicating insufficient variability for statistical analysis.\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] Japanese\n9 Levels: American Indian or Alaska Native Black/African American ... White\n```\n:::\n:::\n\n- Table shows the coefficient of each races to the key predictor  \n\n::: {.cell}\n::: {.cell-output-display}\n|RACE                             | log_INCTOT_Coefficient|\n|:--------------------------------|----------------------:|\n|American Indian or Alaska Native |              0.0937685|\n|Black/African American           |              0.0621126|\n|Chinese                          |              0.1915177|\n|Other Asian or Pacific Islander  |              0.1050231|\n|Other race, nec                  |              0.0376731|\n|Three or more major races        |              0.1048730|\n|Two major races                  |              0.0882288|\n|White                            |              0.1676538|\n:::\n:::\n\nAnalysis to the table:\n- The **Chinese** group exhibits the highest log_INCTOT coefficient, indicating the strongest positive association between income and the variable of interest in this dataset.\n  \n- **American Indian or Alaska Native**, **Other Asian or Pacific Islander**, **Other race, nec**, **Three or more major races**, and **White** categories display coefficients ranging from approximately 0.0376 to 0.1676, suggesting varied degrees of positive association between income and the variable measured.\n\n- The **Black/African American** and **Two major races** groups have relatively lower coefficients of approximately 0.0621 and 0.0882, respectively, implying a weaker positive relationship compared to the other groups.\n\n- There is no negative coefficient present, which would indicate a negative relationship between income and the variable; all listed races have positive coefficients, implying a positive relationship across the board.\n\n### Year 2000-2022\n### For each race, how the coefficient change across 2000 to 2022 \n- Confimed that RACE is a factor and has at least two levels. \n\n::: {.cell}\n\n```{.r .cell-code}\ndata_twenty$RACE <- factor(data_twenty$RACE)\nif (length(levels(data_twenty$RACE)) < 2) {\n  stop(\"RACE must have at least two levels\")\n}\n```\n:::\n\n\n- No need to drop because all has more than one level. \n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert categorical variables to factors\ncategorical_vars <- c(\"KITCHEN\", \"MARST\", \"EMPSTAT\", \"REGION_CLASSIFIED\")\ndata_twenty[categorical_vars] <- lapply(data_twenty[categorical_vars], factor)\n\n# Convert categorical variables to factors\ncategorical_vars <- c(\"KITCHEN\", \"MARST\", \"EMPSTAT\", \"REGION_CLASSIFIED\")\ndata_twenty[categorical_vars] <- lapply(data_twenty[categorical_vars], factor)\n\n# Check the number of levels per categorical variable within each RACE group\nrace_levels <- data_twenty %>%\n  group_by(RACE) %>%\n  summarize(across(all_of(categorical_vars), ~n_distinct(.))) %>%\n  ungroup()\n\n# Identify RACE groups with any categorical variable having only one level\nraces_with_single_levels <- race_levels %>%\n  filter(if_any(everything(), ~.x == 1)) %>%\n  pull(RACE) # Extract the RACE values with problematic levels\n\n# Filter out the problematic RACE groups from the main dataset\ndata_twenty_filtered <- data_twenty %>%\n  filter(!RACE %in% races_with_single_levels)\nprint(races_with_single_levels)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfactor()\n9 Levels: American Indian or Alaska Native Black/African American ... White\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert categorical variables to factors again after subsetting just in case\ndata_twenty_filtered[categorical_vars] <- lapply(data_twenty_filtered[categorical_vars], factor)\n\n# Check the number of levels per categorical variable within each RACE-YEAR group\nrace_year_levels <- data_twenty_filtered %>%\n  group_by(RACE, YEAR) %>%\n  summarize(across(all_of(categorical_vars), ~n_distinct(.))) %>%\n  ungroup()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'RACE'. You can override using the\n`.groups` argument.\n```\n:::\n\n```{.r .cell-code}\n# Identify RACE-YEAR groups with any categorical variable having only one level\nrace_year_with_single_levels <- race_year_levels %>%\n  filter(if_any(everything(), ~.x == 1)) \n\n# Display the RACE-YEAR groups with issues, if any\nprint(race_year_with_single_levels)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 58 × 6\n   RACE                             YEAR KITCHEN MARST EMPSTAT REGION_CLASSIFIED\n   <fct>                           <dbl>   <int> <int>   <int>             <int>\n 1 American Indian or Alaska Nati…  2000       1     2       3                 4\n 2 American Indian or Alaska Nati…  2002       1     4       3                 4\n 3 American Indian or Alaska Nati…  2003       1     4       3                 4\n 4 American Indian or Alaska Nati…  2004       1     4       3                 3\n 5 American Indian or Alaska Nati…  2006       1     6       3                 4\n 6 American Indian or Alaska Nati…  2010       1     5       3                 4\n 7 American Indian or Alaska Nati…  2019       1     5       3                 4\n 8 Black/African American           2001       1     6       3                 4\n 9 Chinese                          2000       1     3       2                 3\n10 Chinese                          2002       1     4       3                 3\n# ℹ 48 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter out the problematic RACE-YEAR groups from the main dataset\ndata_twenty_filtered_final <- data_twenty_filtered %>%\n  anti_join(race_year_with_single_levels, by = c(\"RACE\", \"YEAR\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Now, with the cleaned data, fit the models\nmodels_by_race_year <- data_twenty_filtered_final %>%\n  group_by(RACE, YEAR) %>%\n  do(\n    model = lm(log_RENTGRS ~ log_INCTOT + KITCHEN + ROOMS + NFAMS + AGE + MARST + EMPSTAT + REGION_CLASSIFIED, data = .)\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodels_with_coef <- models_by_race_year %>%\n  rowwise() %>% \n  mutate(log_INCTOT_coef = coef(model)[[\"log_INCTOT\"]]) %>%\n  ungroup() %>%\n  select(RACE, YEAR, log_INCTOT_coef)\n\ncoefficients_wide <- models_with_coef %>%\n  pivot_wider(names_from = RACE, values_from = log_INCTOT_coef, names_prefix = \"coef_\")\n\nkable(coefficients_wide)\n```\n\n::: {.cell-output-display}\n| YEAR| coef_American Indian or Alaska Native| coef_Black/African American| coef_Chinese| coef_Japanese| coef_Other Asian or Pacific Islander| coef_Other race, nec| coef_Three or more major races| coef_Two major races| coef_White|\n|----:|-------------------------------------:|---------------------------:|------------:|-------------:|------------------------------------:|--------------------:|------------------------------:|--------------------:|----------:|\n| 2001|                             0.0044494|                          NA|    0.0097707|            NA|                            0.1221862|            0.0818381|                             NA|            0.1007001|  0.1445229|\n| 2005|                            -0.1728914|                   0.0873527|    0.1326179|            NA|                            0.0897322|            0.0429701|                             NA|                   NA|  0.1379574|\n| 2007|                             0.1239418|                   0.1115806|           NA|            NA|                            0.0864570|            0.1019018|                             NA|            0.0988822|  0.1401784|\n| 2008|                             0.1662273|                   0.0717442|           NA|            NA|                            0.0495650|            0.0811385|                             NA|            0.0705536|  0.1261771|\n| 2009|                            -0.0290841|                   0.0982650|    0.0462740|            NA|                            0.0979882|            0.1357880|                             NA|            0.0883666|  0.1215903|\n| 2011|                            -0.0246266|                   0.1289264|    0.1080701|    -0.3049829|                            0.1056626|            0.0704745|                             NA|            0.0950769|  0.1434630|\n| 2012|                             0.0829896|                   0.0815911|    0.1408589|     0.2402733|                            0.0947194|            0.0336927|                             NA|            0.0447647|  0.1477391|\n| 2013|                             0.1450099|                   0.1208850|           NA|     0.3074672|                            0.0719337|            0.0944647|                             NA|            0.1077284|  0.1413223|\n| 2014|                            -0.0806190|                   0.0774011|    0.1243816|     0.1948937|                            0.1704745|            0.0192973|                     -0.0246775|            0.0501507|  0.1423022|\n| 2015|                             0.2288886|                   0.0866523|    0.1437636|            NA|                            0.0588220|            0.0124419|                     -0.0798592|            0.0240695|  0.1366126|\n| 2016|                             0.0724100|                   0.1070357|    0.0935354|            NA|                            0.0892159|            0.0831495|                             NA|            0.1105840|  0.1281357|\n| 2017|                             0.1140436|                   0.1154084|    0.0120262|     0.0758910|                            0.0610027|            0.1443399|                             NA|            0.0379656|  0.1514833|\n| 2018|                             0.1443089|                   0.1216139|    0.2833792|            NA|                            0.1070153|            0.0425257|                      0.3835364|            0.1375949|  0.1594088|\n| 2020|                             0.0264148|                   0.0821522|    0.0947932|            NA|                            0.1345643|            0.1008466|                             NA|            0.0531118|  0.1628788|\n| 2021|                            -0.0599569|                   0.0664240|    0.1149156|            NA|                            0.1242797|            0.0334209|                     -0.0382770|            0.0856113|  0.1649109|\n| 2022|                             0.0984965|                   0.0632937|    0.2196783|            NA|                            0.1033151|            0.0390094|                      0.0722550|            0.0800541|  0.1637250|\n| 2000|                                    NA|                   0.0358345|           NA|            NA|                                   NA|                   NA|                             NA|                   NA|  0.1459856|\n| 2002|                                    NA|                   0.0994888|           NA|            NA|                                   NA|            0.1131498|                             NA|                   NA|  0.1290758|\n| 2003|                                    NA|                   0.1201889|           NA|            NA|                            0.0611945|            0.0426896|                             NA|           -0.0781177|  0.1278780|\n| 2004|                                    NA|                   0.1245230|    0.0048313|            NA|                            0.0655594|                   NA|                             NA|            0.0013052|  0.1292762|\n| 2006|                                    NA|                   0.1192481|    0.0993890|     0.4505390|                            0.1058852|            0.0840827|                             NA|                   NA|  0.1273188|\n| 2010|                                    NA|                   0.0965021|           NA|    -0.8670287|                            0.1104422|            0.0597122|                             NA|            0.0686506|  0.1432963|\n| 2019|                                    NA|                   0.1027066|    0.2814538|            NA|                            0.1331487|            0.0892457|                             NA|                   NA|  0.1464698|\n:::\n:::\n\n- Specific Trends:\n\n**Alaska Native**: Shows minor fluctuations around zero, with both positive and negative coefficients, indicating inconsistent trends over the years.\n\n**American**: This category has NA values, suggesting incomplete data, making it hard to discern a clear trend.\n\n**Chinese**: Generally has higher positive coefficients compared to other groups, particularly noticeable in later years, indicating a strong positive association with income in those years.\n\n**Japanese**: Has some missing values but otherwise presents mostly positive coefficients, with a notable spike in recent years.\n\n**Islander**: Also features both positive and negative coefficients with considerable variability.\n\n**Other race, nec**: Shows a mix of positive, negative, and NA values, making a clear trend difficult to establish.\n\n**Two or more races**: This group generally has positive coefficients, with a few exceptions, suggesting a fairly consistent positive association with income.\n\n**Whites**: Present a range of coefficients, mostly positive with some fluctuations, but generally indicate a positive association with income.\n\n- Race Comparisons: Certain racial categories, like those identifying as Chinese and Japanese, tend to have higher coefficients, suggesting a stronger relationship with income than other races in the dataset. Conversely, the 'Other race, nec' category often has lower coefficients, implying a weaker association with income.\n\n::: {.cell}\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}